const CATS = {
adventure:{label:'Adventure',emoji:'🏕️',c1:'#ff8a4c',c2:'#d4622a',glow:'rgba(255,138,76,.35)',ideas:[
{t:"Get off at a train stop you've never heard of and explore it",s:"Somebody's favourite café is probably hiding there",tags:['Solo','Friends','Outdoors','City','Nature','Free','Half day','Chill','Adventure']},
{t:"Find the place with the weirdest name within 50km and go see it",s:"There's only one way to find out why it's called that",tags:['Solo','Friends','Road Trip','Under €10','Full day','Chill','Adventure']},
{t:"Jump into a nearby lake or sea",s:"Your nervous system is about to receive important news",tags:['Friends','Couple','Outdoors','Nature','Free','30min','High Energy','Adventure']},
{t:"Zoom out on Google Maps and pick somewhere random to go today",s:"Today's destination has been selected by fate",tags:['Friends','Solo','Road Trip','Under €10','Full day','Active','Adventure']},
{t:"Go horseback riding",s:"Yeah I'm gonna take my horse to the…",tags:['Friends','Couple','Outdoors','Nature','Under €50','Half day','Active','Adventure']},
{t:"Sleep in a tent",s:'Hotels are nice, but bears make memories',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Chill','Adventure']},
{t:"Try climbing or bouldering",s:"Don't look down… don't look down…",tags:['Friends','Solo','Outdoors','Nature','Under €20','Half day','High Energy','Adventure']},
{t:"Go cliff jumping",s:'Brain says AAH, you say AAAAAAH',tags:['Friends','Outdoors','Nature','Free','Half day','High Energy','Adventure']},
{t:"Find the scariest ride in the amusement park",s:'Who will scream the loudest?',tags:['Friends','Family','City','Under €50','Full day','High Energy','Adventure']},
{t:"Try scuba diving",s:'ATLANTIS HERE WE COME',tags:['Friends','Couple','Outdoors','Nature','Under €50','Half day','Active','Adventure']},
{t:"Take a helicopter ride",s:'Expensive? Yes. Once in a lifetime? Also yes',tags:['Friends','Couple','Nature','City','Expensive','Half day','Chill','Adventure']},
{t:"You could go fishing",s:'The supermarket has made us soft',tags:['Friends','Solo','Outdoors','Nature','Free','Full day','Lazy','Adventure']},
{t:"Rent a boat for a day",s:'Getting stranded in the middle of the sea with friends?! FUN',tags:['Friends','Outdoors','Nature','Under €50','Full day','Chill','Adventure']},
{t:"Try surfing",s:'Radical…',tags:['Friends','Solo','Outdoors','Nature','Under €50','Full day','High Energy','Adventure']},
{t:"Sleep somewhere weird",s:'Treehouse. Lighthouse. Castle. Go crazy with it',tags:['Friends','Couple','Outdoors','Nature','Under €50','Multiple days','Chill','Adventure']},
{t:"Climb a mountain",s:"Preferably don't start with Everest",tags:['Friends','Solo','Outdoors','Nature','Free','Full day','High Energy','Adventure']},
{t:"Hike through some pretty trails",s:'Pretty views, delicious snacks, healthy choices',tags:['Friends','Solo','Family','Outdoors','Nature','Free','Full day','Active','Adventure']},
{t:"Go night swimming",s:"The sea gets way bigger when you can't see the bottom",tags:['Friends','Couple','Outdoors','Nature','Free','1 hour','Active','Adventure']},
{t:"Board the next train or bus without checking where it's going",s:'Future you can figure it out',tags:['Solo','Friends','City','Under €10','Full day','Chill','Adventure']},
{t:"Drive somewhere with zero light pollution",s:'Stars are kind of ridiculous without street lamps competing',tags:['Friends','Couple','Outdoors','Nature','Under €10','Evening','Chill','Adventure']},
{t:"Buy the cheapest ticket to another country and spend a day there",s:'Tristan da Cunha people will not like this one',tags:['Friends','Solo','Couple','Road Trip','Under €50','Multiple days','Active','Adventure']},
{t:"Get on a train with no return ticket",s:'Future you seems like a capable guy',tags:['Solo','Friends','Road Trip','Under €20','Multiple days','Active','Adventure']},
{t:"Go skydiving",s:"Momma didn't raise no b****!",tags:['Friends','Solo','Outdoors','Nature','Expensive','Half day','High Energy','Adventure']},
{t:"Find the coldest river nearby and jump in",s:'Everyone acts tough until the first toe enters the water',tags:['Friends','Outdoors','Nature','Free','30min','High Energy','Adventure']},
{t:"Find a cave and go explore it",s:'Or actually take a tour guide? Just saying…',tags:['Friends','Solo','Outdoors','Nature','Under €20','Half day','Active','Adventure']},
{t:"Spend a night in a mountain hut",s:'What was that sound?',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Active','Adventure']},
{t:"Rent jet skis",s:'Childhood dreams and poor financial decisions finally meet',tags:['Friends','Couple','Outdoors','Nature','Expensive','Half day','High Energy','Adventure']},
{t:"Sleep in your car somewhere beautiful",s:'Five-star view, one-star mattress',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','Multiple days','Chill','Adventure']},
{t:"Wake up early to see the sunrise",s:"Don't give me that look…",tags:['Solo','Couple','Friends','Outdoors','Nature','Free','30min','Chill','Adventure']},
{t:"Make a campfire and cook food on it",s:'Bonus points for guitar players',tags:['Friends','Family','Outdoors','Nature','Under €10','Evening','Chill','Adventure']},
{t:"Camp in the rain",s:'Cozy, nature and hot tea — what more do you need?',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Chill','Adventure']},
{t:"Sleep outside with no tent",s:'It looked easier watching Bear Grylls do it',tags:['Friends','Outdoors','Nature','Free','Multiple days','Active','Adventure']},
{t:"Explore abandoned buildings nearby",s:'It was the wind bro, I swear',tags:['Friends','Outdoors','City','Nature','Free','Half day','Active','Scary','Adventure']},
{t:"Ask a stranger for a hidden gem",s:'The real adventure is the friends we made along the way',tags:['Solo','Friends','City','Free','Half day','Chill','Adventure']},
{t:"Try paragliding",s:'The ground looks fake from up here',tags:['Friends','Couple','Outdoors','Nature','Expensive','Half day','High Energy','Adventure']},
{t:"Go kayaking or canoeing",s:'Arms will hurt. Worth it',tags:['Friends','Couple','Solo','Outdoors','Nature','Under €20','Half day','Active','Adventure']},
{t:"Try a via ferrata",s:'Like climbing, but with a safety wire and a whole lot of trust',tags:['Friends','Solo','Outdoors','Nature','Under €20','Full day','High Energy','Adventure']},
{t:"Do a night hike with headlamps",s:'Who dares exploring the woods like this?',tags:['Friends','Outdoors','Nature','Free','Evening','Active','Scary','Adventure']},
{t:"Try rafting with your friends",s:'The river has opinions. Respect them',tags:['Friends','Outdoors','Nature','Under €50','Half day','High Energy','Adventure']},
{t:"Find a waterfall and swim in it",s:"Nature's original infinity pool",tags:['Friends','Couple','Outdoors','Nature','Free','Full day','Active','Adventure']},
{t:"Go mountain biking downhill",s:'Gravity does half the work. Fear does the other half',tags:['Friends','Solo','Outdoors','Nature','Under €50','Half day','High Energy','Adventure']},
{t:"Try an outdoor survival challenge",s:'2-3 days no phone. Now what?',tags:['Friends','Solo','Outdoors','Nature','Under €50','Multiple days','High Energy','Adventure']},
{t:"Go bungee jumping",s:'Your body will file a complaint. Sign it anyway',tags:['Friends','Solo','Outdoors','Nature','Expensive','Half day','High Energy','Adventure']},
{t:"Find a local legend or folklore location and visit it",s:'Every town has a story. Go find yours',tags:['Friends','Solo','Outdoors','Nature','City','Free','Half day','Chill','Adventure']},
{t:"Rent motorbikes or bikes for the day and explore",s:'Wind in your hair, poor decisions ahead',tags:['Friends','Couple','Road Trip','Under €50','Full day','Active','Adventure']},
{t:"Try coasteering",s:'Jumping off rocks into the sea like nature intended',tags:['Friends','Outdoors','Nature','Under €20','Half day','High Energy','Adventure']},
{t:"Build a raft and actually test it",s:'Minecraft logic meets real consequences',tags:['Friends','Outdoors','Nature','Under €10','Full day','Active','Crazy','Adventure']},
{t:"Do something you've always been too scared to do",s:'You already know what it is',tags:['Solo','Friends','Varies','Varies','High Energy','Adventure']},
{t:"Seek for geodes or other natural treasures",s:'The earth has been hiding things. Time to find them',tags:['Friends','Family','Solo','Outdoors','Nature','Free','Half day','Active','Adventure']},
{t:"Open Google Earth and explore somewhere you've never been",s:'Basically free travel',tags:['Solo','Home','Indoors','Free','30min','Lazy','Adventure']},
{t:"Find the most remote place on Google Maps and zoom in",s:'Some of those places have zero roads. Zero people.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Adventure']},
{t:"Find the nearest place you've never been and go there on foot",s:'Could be 5 minutes away. Could be life-changing. Probably not.',tags:['Solo','Outdoors','Free','1 hour','Chill','Adventure']},
{t:"90s trip!",s:'Maps, analog cameras and getting lost.',tags:['Friends','Couple','Outdoors','Road Trip','Under €50','Multiple days','Active','Adventure']},
{t:"Budget trip!",s:'3+ days, 50€, creativity begins where money ends.',tags:['Friends','Couple','Outdoors','Road Trip','Under €50','Multiple days','Active','Adventure']},
{t:"RNG trip",s:'Every major decision gets decided by spin the wheel. Left or right? Restaurant? Beach?',tags:['Friends','Couple','Outdoors','Road Trip','Varies','Multiple days','Active','Adventure']},
{t:"No cars trip",s:'Train. Bus. Ferry. Walking. Humans did this before.',tags:['Friends','Couple','Outdoors','Road Trip','Varies','Multiple days','Active','Adventure']},
{t:"Hitchhiking trip!",s:'That scary trucker probably has a softer side.',tags:['Friends','Couple','Outdoors','Road Trip','Free','Multiple days','Active','Adventure']},
{t:"Car camping trip!",s:'Five-star views. One-star mattresses.',tags:['Friends','Couple','Outdoors','Nature','Under €50','Multiple days','Chill','Adventure']},
{t:"Cheapest plane ticket trip!",s:'Buy the cheapest ticket currently available and go there.',tags:['Friends','Couple','Outdoors','Road Trip','Varies','Multiple days','High Energy','Adventure']},
{t:"Mystery trip!",s:"One person plans everything. Nobody else gets to know where you're going.",tags:['Friends','Couple','Outdoors','Road Trip','Varies','Multiple days','Active','Adventure']},
]},
chill:{label:'Chill',emoji:'☁️',c1:'#5fd4c4',c2:'#2a9d8f',glow:'rgba(95,212,196,.35)',ideas:[
{t:"Find a pretty spot and listen to music",s:"Sometimes that's enough",tags:['Solo','Couple','Outdoors','Nature','City','Free','1 hour','Lazy','Chill']},
{t:"Read a book outside",s:'Books somehow hit different in nature',tags:['Solo','Outdoors','Nature','Free','Half day','Lazy','Romantic','Chill']},
{t:"Make the best hot chocolate you possibly can",s:"We're going for Michelin stars today",tags:['Solo','Friends','Home','Indoors','Under €5','30min','Lazy','Chill']},
{t:"Try meditating for 10 minutes",s:'Your brain could use a coffee break',tags:['Solo','Home','Indoors','Free','15min','Lazy','Chill']},
{t:"Stretch for 15 minutes",s:'Your back has been sending complaints',tags:['Solo','Home','Indoors','Free','15min','Lazy','Chill']},
{t:"Watch the sunset and talk about life",s:'In all the chaos, a blink of calm',tags:['Couple','Friends','Outdoors','Nature','Free','1 hour','Lazy','Romantic','Chill']},
{t:"Go for a walk with no destination",s:"It's to appreciate the details around you",tags:['Solo','Couple','Outdoors','City','Nature','Free','1 hour','Chill']},
{t:"Sit around a campfire",s:"It's kind of hypnotic",tags:['Friends','Couple','Outdoors','Nature','Under €10','Evening','Lazy','Chill']},
{t:"Pet an animal and forget about life for a bit",s:'They seem to have it figured out',tags:['Solo','Couple','Outdoors','Nature','City','Free','30min','Lazy','Chill']},
{t:"Find some bugs outside",s:'There is so much going on all around us',tags:['Solo','Family','Outdoors','Nature','Free','30min','Lazy','Chill']},
{t:"Make your own jewellery",s:'Just find a rock, shape it, string through it — easier than it seems',tags:['Solo','Friends','Home','Indoors','Under €5','Half day','Lazy','Chill']},
{t:"Visit a cozy café and order some tea or coffee",s:'Bring a book, a friend, or just stare at life happening around you',tags:['Solo','Couple','City','Under €5','Half day','Lazy','Chill']},
{t:"Lie in the grass and watch the clouds",s:'Cloud engineers deserve recognition',tags:['Solo','Couple','Outdoors','Nature','Free','30min','Lazy','Chill']},
{t:"Make tea and just stare out the window",s:'Grandma energy. Embrace it',tags:['Solo','Home','Indoors','Under €5','15min','Lazy','Chill']},
{t:"Take the longest shower known to mankind",s:'Ideas have been born here',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Light a scented candle and turn off the lights",s:'Combine that with a movie, snacks and a warm drink',tags:['Solo','Couple','Home','Indoors','Under €10','Evening','Lazy','Chill']},
{t:"Buy a plant",s:"Congratulations, you're responsible for a life now",tags:['Solo','Couple','City','Under €10','1 hour','Lazy','Chill']},
{t:"Sit under a tree",s:'People used to call this an afternoon',tags:['Solo','Couple','Outdoors','Nature','Free','Half day','Lazy','Chill']},
{t:"Listen to an album from start to finish",s:'No skipping. Trust the artist',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Chill']},
{t:"Buy an analog camera and take some photos",s:"Every photo counts, that's what makes it special",tags:['Solo','Friends','Couple','Outdoors','City','Nature','Under €20','Half day','Chill']},
{t:"Bake something",s:'Your house deserves to smell amazing',tags:['Solo','Friends','Home','Indoors','Under €10','Half day','Chill']},
{t:"Eat breakfast outside",s:'The birds have been doing this forever',tags:['Solo','Couple','Outdoors','Nature','Under €10','30min','Lazy','Chill']},
{t:"Do a puzzle together",s:'Your grandparents knew what they were doing',tags:['Friends','Couple','Family','Home','Indoors','Under €10','Half day','Lazy','Chill']},
{t:"Make something out of clay",s:'Elementary school vibes',tags:['Solo','Friends','Home','Indoors','Under €10','Half day','Lazy','Chill']},
{t:"Call someone you haven't talked to in a while",s:'Do not overthink. Just call them',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Maybe you just need a nap",s:'No seriously',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Chill']},
{t:"Write a postcard to someone",s:'Very meaningful and very underrated',tags:['Solo','Home','Indoors','Under €5','30min','Lazy','Chill']},
{t:"Movie night",s:'Popcorn, friends and a great movie',tags:['Friends','Couple','Home','Indoors','Under €10','Evening','Lazy','Chill']},
{t:"Stargaze at a spot with no light pollution",s:'This is peak chill',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','Evening','Lazy','Romantic','Chill']},
{t:"Buy some drinks and find a chill spot",s:'An evergreen combo',tags:['Friends','Couple','Outdoors','Nature','City','Under €10','Evening','Lazy','Chill']},
{t:"Look through an old photo album",s:'Ah, the nostalgia',tags:['Solo','Family','Home','Indoors','Free','30min','Lazy','Nostalgic','Chill']},
{t:"Visit a bakery early in the morning",s:'Something about the smell just fixes people',tags:['Solo','Couple','City','Under €5','30min','Lazy','Chill']},
{t:"Start a tiny herb garden",s:"Congratulations. You're basically a medieval healer now",tags:['Solo','Home','Indoors','Under €10','1 hour','Lazy','Chill']},
{t:"Rearrange your room or buy new decorations",s:'Sometimes your room needs character development too',tags:['Solo','Home','Indoors','Under €20','Half day','Chill']},
{t:"Put on headphones and listen to your favourite songs with your eyes closed",s:'Let the music take you somewhere else',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Order way too much food and regret nothing",s:"Leftovers are tomorrow's problem",tags:['Friends','Couple','Home','Indoors','Under €20','Evening','Lazy','Chill']},
{t:"Go for a late night drive",s:'No destination. Just vibes',tags:['Friends','Couple','Solo','Road Trip','Under €10','Evening','Lazy','Crazy','Chill']},
{t:"Play board games",s:'They are actually still very fun',tags:['Friends','Family','Home','Indoors','Free','Half day','Lazy','Chill']},
{t:"Buy random snacks and rate them",s:'Democracy but for snacks',tags:['Friends','Couple','Home','Indoors','Under €10','1 hour','Lazy','Chill']},
{t:"Retro games night",s:'8-bit sounds and old memories',tags:['Friends','Couple','Home','Indoors','Free','Evening','Lazy','Nostalgic','Chill']},
{t:"Go for a walk and talk about life",s:'Therapy, but cheaper',tags:['Friends','Couple','Outdoors','City','Nature','Free','1 hour','Chill']},
{t:"Play some video games with a friend",s:'Core childhood memories unlocked',tags:['Friends','Home','Indoors','Free','Half day','Lazy','Nostalgic','Chill']},
{t:"Find a hammock spot and just exist for a while",s:'Horizontal is a valid life choice',tags:['Solo','Couple','Outdoors','Nature','Free','Half day','Lazy','Chill']},
{t:"Cook a proper meal from scratch with no shortcuts",s:'Turns out your phone has recipes, not just doom',tags:['Solo','Couple','Home','Indoors','Under €20','Half day','Chill']},
{t:"Watch the rain from somewhere warm",s:'One of those simple things that just works',tags:['Solo','Couple','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Write down everything that's on your mind",s:'No structure, no goal. Just get it out',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Sit in a park and just people-watch",s:'Humans are fascinating when you stop being one of them',tags:['Solo','Couple','Outdoors','City','Free','1 hour','Lazy','Chill']},
{t:"Make a playlist for a specific feeling",s:'Not a vibe. A very specific feeling at 11pm on a Tuesday',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Find a field and just lie in it",s:'No agenda. No phone. Just sky',tags:['Solo','Couple','Outdoors','Nature','Free','1 hour','Lazy','Chill']},
{t:"Do absolutely nothing and be okay with it",s:'Revolutionary concept',tags:['Solo','Home','Indoors','Free','Half day','Lazy','Chill']},
{t:"Find the most relaxing YouTube video and just watch it",s:'Fireplace, rain on a window, Bob Ross — your call',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Think about 3 things that made you happy this week",s:'Sounds cheesy. Works anyway.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Chill']},
{t:"Change your phone wallpaper",s:'Small thing. Weirdly effective.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Chill']},
{t:"Wikipedia rabbit hole",s:'Start on anything. See where you end up in 30 minutes.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Chill']},
{t:"Make your bed perfectly and then immediately lie in it",s:'The satisfaction is real',tags:['Solo','Home','Indoors','Free','15min','Lazy','Chill']},
{t:"Watch old cartoons",s:'No context needed',tags:['Solo','Home','Indoors','Free','30min','Lazy','Nostalgic','Chill']},
{t:"Find a lo-fi playlist and just exist",s:'No agenda. Just vibes.',tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Chill']},
{t:"Order some food and chill",s:'Sometimes the move is the obvious one',tags:['Solo','Couple','Home','Indoors','Under €20','Evening','Lazy','Chill']},
]},
fun:{label:'Fun',emoji:'🎉',c1:'#ffd23f',c2:'#f0a500',glow:'rgba(255,210,63,.35)',ideas:[
{t:"Go to a karaoke bar",s:"The ones who say they can't sing always go the hardest",tags:['Friends','City','Under €20','Evening','Active','Fun']},
{t:"Go to an escape room",s:'If there are 4 you can pick a hidden impostor to sabotage your escape!',tags:['Friends','Couple','City','Under €20','1 hour','Chill','Fun']},
{t:"Host a cooking competition at home",s:'Gordon Ramsay energy, student budget ingredients',tags:['Friends','Home','Indoors','Under €20','Half day','Active','Fun']},
{t:"Do a pub quiz",s:'That one friend who knows random facts finally gets to shine',tags:['Friends','City','Under €10','Evening','Lazy','Fun']},
{t:"Play mini golf",s:'Surprisingly competitive. Someone will take it too seriously',tags:['Friends','Couple','Family','City','Under €10','1 hour','Chill','Fun']},
{t:"Play beer pong",s:'The rules are simple. The consequences are not',tags:['Friends','Home','Indoors','Under €10','Evening','Active','Fun']},
{t:"Play truth or dare",s:'The questions can be pretty bad',tags:['Friends','Home','Indoors','Free','Evening','Chill','Fun']},
{t:"Host a campfire night and cook some food",s:'Bonus points for guitar players',tags:['Friends','Family','Outdoors','Nature','Under €10','Evening','Chill','Fun']},
{t:"Race with shopping carts",s:'We were just borrowing them!',tags:['Friends','City','Free','30min','High Energy','Fun']},
{t:"Host a PowerPoint night",s:'The topics can be as deluded as you want',tags:['Friends','Home','Indoors','Free','Evening','Lazy','Fun']},
{t:"Mouth filled with water — you laugh you lose",s:'Sit face to face and die laughing',tags:['Friends','Couple','Home','Indoors','Free','30min','Lazy','Fun']},
{t:"Make your own go-karts and race with them",s:"It's basically human Mario Kart",tags:['Friends','Outdoors','Under €20','Half day','High Energy','Fun']},
{t:"You have 15 minutes — find the weirdest thing for under €10",s:'No rules. No limits. No refunds',tags:['Friends','City','Under €10','30min','Active','Fun']},
{t:"Blindfold taste test",s:'Coke vs Pepsi wars begin today',tags:['Friends','Couple','Home','Indoors','Under €10','1 hour','Lazy','Fun']},
{t:"Water balloon war",s:'The Geneva Convention says nothing about this',tags:['Friends','Family','Outdoors','Under €10','1 hour','High Energy','Summer','Fun']},
{t:"Paintball",s:'Everybody becomes John Wick for an hour and gets a lot of bruises',tags:['Friends','Outdoors','City','Nature','Under €50','Half day','High Energy','Fun']},
{t:"Theme night",s:'Cowboys? Mafia? Hawaiian shirts? Sky is the limit!',tags:['Friends','Home','Indoors','Under €20','Evening','Chill','Fun']},
{t:"Build paper airplanes and compete",s:'Aerospace engineers start somewhere',tags:['Friends','Family','Home','Indoors','Outdoors','Free','1 hour','Lazy','Fun']},
{t:"Board game night",s:'Friendships are temporary. Victory is forever',tags:['Friends','Family','Home','Indoors','Under €10','Evening','Lazy','Fun']},
{t:"Build something stupid together",s:'Maximum creativity. Minimum engineering',tags:['Friends','Home','Indoors','Under €10','Half day','Active','Fun']},
{t:"Decide for each other what to wear and actually wear it in public",s:'Also a great punishment for losing a challenge',tags:['Friends','City','Free','Half day','Chill','Fun']},
{t:"Host a cocktail night",s:'The hardest part is finding the ingredients',tags:['Friends','Home','Indoors','Under €20','Evening','Chill','Fun']},
{t:"Everybody brings one mystery ingredient and you cook with all of them",s:'No veto rights. No complaints',tags:['Friends','Home','Indoors','Under €20','Half day','Active','Fun']},
{t:"Go to the arcade",s:'Your wallet is weaker than your inner child',tags:['Friends','Couple','Family','City','Under €20','Half day','Active','Fun']},
{t:"Everyone gets one random object and must sell it within an hour",s:'Shark Tank energy',tags:['Friends','Home','Indoors','City','Free','1 hour','Active','Fun']},
{t:"Rock paper scissors — losers get a challenge picked by everyone else",s:'This is how gambling addictions start',tags:['Friends','Home','Indoors','Free','30min','Lazy','Fun']},
{t:"Find a free event happening in your city and crash it",s:"They're everywhere and nobody checks",tags:['Friends','Solo','City','Free','Half day','Chill','Fun']},
{t:"Everybody orders food for the person on their left",s:'Trust issues included',tags:['Friends','Home','Indoors','City','Under €20','Half day','Lazy','Fun']},
{t:"Buy drinks and snacks you've never tried and rank them",s:'Some countries owe apologies',tags:['Friends','Couple','Home','Indoors','Under €20','1 hour','Lazy','Fun']},
{t:"Have a mukbang at a fast food restaurant",s:'Or bring the food to a spot that actually slaps',tags:['Friends','City','Nature','Under €20','Half day','Lazy','Fun']},
{t:"Go to a thrift shop and find some cool clothes",s:'Grandmas and grandpas had some serious drip',tags:['Friends','Couple','City','Under €10','Half day','Chill','Fun']},
{t:"Be fashion designers for each other",s:'You can actually try to give good advice here',tags:['Friends','Couple','Home','Indoors','Free','1 hour','Lazy','Fun']},
{t:"Take a day trip — pick any location",s:'No overthinking. Just go',tags:['Friends','Couple','Road Trip','Under €20','Full day','Chill','Fun']},
{t:"Explore a cool place with bikes only",s:'Childhood memories here we come',tags:['Friends','Couple','Family','Outdoors','City','Nature','Free','Half day','Active','Fun']},
{t:"Play hide and seek but the seeker has water balloons",s:'Full of adrenaline, full of laughs',tags:['Friends','Family','Outdoors','Under €10','1 hour','High Energy','Summer','Fun']},
{t:"Play Among Us IRL",s:'Spread tasks across the house, murderer kills by tapping you twice',tags:['Friends','Home','Indoors','Free','1 hour','Active','Fun']},
{t:"Have a picnic and bring some card games",s:'Simple and effective',tags:['Friends','Couple','Family','Outdoors','Nature','Under €10','Half day','Lazy','Fun']},
{t:"Have a BBQ party",s:'Great food and even greater friends',tags:['Friends','Family','Outdoors','Under €20','Half day','Chill','Summer','Fun']},
{t:"Everybody gets €5 and buys a mystery gift for someone else",s:'The thought counts. Allegedly',tags:['Friends','City','Under €10','Half day','Chill','Fun']},
{t:"Seek for geodes or other natural treasures",s:'The earth has been hiding things. Time to find them',tags:['Friends','Family','Solo','Outdoors','Nature','Free','Half day','Active','Fun']},
{t:"Drive somewhere absurdly far for one specific food item",s:'Two hours for nuggets? Absolutely',tags:['Friends','Couple','Road Trip','Under €20','Full day','Chill','Fun']},
{t:"Hide 100 tiny objects around a friend's house without them knowing",s:'Months later they will still be finding them',tags:['Friends','Home','Indoors','Free','1 hour','Lazy','Fun']},
{t:"Send some memes to your friends",s:'No context. Just send it.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Fun']},
{t:"Try to draw someone from memory and send it to them",s:'It will be terrible. That is the point.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Fun']},
{t:"Find 1-star reviews on Google Maps nearby",s:'People are unhinged and it is beautiful',tags:['Solo','Home','Indoors','Free','15min','Lazy','Fun']},
{t:"Find the worst rated movies and watch one",s:'The comments will be better than the film',tags:['Solo','Home','Indoors','Free','15min','Lazy','Fun']},
{t:"Watch something funny on YouTube",s:'Falls, fails, or stand-up — you pick',tags:['Solo','Home','Indoors','Free','30min','Lazy','Fun']},
{t:"Talk to strangers and make things up about your friends",s:'They must go along with it. No breaking character.',tags:['Friends','City','Outdoors','Free','Half day','High Energy','Fun']},
{t:"Wear white T-shirts and markers and ask strangers to draw on you",s:'Some will be artists. Most will not.',tags:['Friends','City','Outdoors','Under €10','Half day','Active','Fun']},
{t:"Find a sidekick and spend some time with them",s:'Pick a stranger. Make them your companion for the hour.',tags:['Solo','City','Outdoors','Free','1 hour','Active','Fun']},
{t:"Start a random Facebook event and gather as many people as possible",s:'See who actually shows up.',tags:['Friends','City','Outdoors','Free','Half day','Active','Fun']},
{t:"Invite strangers to play truth or dare",s:'The good ones will say yes.',tags:['Friends','City','Outdoors','Free','1 hour','High Energy','Fun']},
{t:"Try to raise 100€ with your friends by selling random stuff",s:'Garage sale meets chaos.',tags:['Friends','City','Outdoors','Free','Half day','Active','Fun']},
]},
romantic:{label:'Romantic',emoji:'❤️',c1:'#ff6b9d',c2:'#e0457a',glow:'rgba(255,107,157,.35)',ideas:[
{t:"Massage each other",s:'No special skills needed, just good intentions',tags:['Couple','Home','Indoors','Free','30min','Lazy','Romantic']},
{t:"Ice cream date",s:'Simple, sweet, never fails',tags:['Couple','City','Under €10','1 hour','Chill','Romantic']},
{t:"Grab a picnic blanket and find a romantic spot to chill",s:'Snacks, sunshine, and zero plans',tags:['Couple','Outdoors','Nature','Under €10','Half day','Lazy','Romantic']},
{t:"Make a necklace or bracelet for your SO",s:'Handmade beats store-bought every time',tags:['Couple','Home','Indoors','Under €10','1 hour','Lazy','Romantic']},
{t:"Bake them something",s:'The smell of effort is underrated',tags:['Couple','Home','Indoors','Under €10','Half day','Chill','Romantic']},
{t:"Take them on a surprise date",s:'Plan everything. Reveal nothing',tags:['Couple','City','Varies','Half day','Chill','Romantic']},
{t:"Learn constellations and watch the stars together",s:'Suddenly the sky means something',tags:['Couple','Outdoors','Nature','Free','Evening','Lazy','Romantic']},
{t:"Art date — draw, paint or work with clay",s:"You'll both be bad at it. That's the fun part",tags:['Couple','Home','Indoors','City','Under €20','Half day','Chill','Romantic']},
{t:"Take them where you first met and reminisce",s:'Full circle moments hit different',tags:['Couple','City','Free','Half day','Chill','Romantic']},
{t:"Surprise them with a small gift today",s:"No occasion needed. That's what makes it good",tags:['Couple','City','Under €10','30min','Chill','Romantic']},
{t:"Take them to their favorite restaurant",s:'Sometimes the classics just work',tags:['Couple','City','Under €50','Half day','Chill','Romantic']},
{t:"Cook a full meal together from scratch",s:'Pick a cuisine neither of you has tried before',tags:['Couple','Home','Indoors','Under €20','Half day','Chill','Romantic']},
{t:"Recreate your first date as closely as possible",s:'Same place, same order, same energy',tags:['Couple','City','Varies','Half day','Chill','Romantic']},
{t:"Find the highest point near your city and watch the sunset",s:'The view is better with someone next to you',tags:['Couple','Outdoors','Nature','City','Free','Evening','Chill','Romantic']},
{t:"Pick them flowers and make a bouquet",s:'Wildflowers count. Effort is the gift',tags:['Couple','Outdoors','Nature','Free','30min','Chill','Romantic']},
{t:"Go somewhere nice with bicycles",s:'Getting lost together is a love language',tags:['Couple','Outdoors','City','Nature','Free','Half day','Active','Romantic']},
{t:"Read to each other",s:"Pick a book. Take turns. It's incredibly intimate for no obvious reason",tags:['Couple','Home','Indoors','Free','1 hour','Lazy','Romantic']},
{t:"Do a spa night at home",s:'Candles, face masks, the whole thing. No irony',tags:['Couple','Home','Indoors','Under €20','Evening','Lazy','Romantic']},
{t:"Have a lazy date",s:'Watch a movie, order your favorite food and chill',tags:['Couple','Home','Indoors','Under €20','Evening','Lazy','Romantic']},
{t:"Dress up and go to a jazz bar",s:'Smooth jazz for a smooth duo',tags:['Couple','City','Under €20','Evening','Chill','Romantic']},
{t:"Take them on a mystery trip",s:'Could be anything. The anticipation is what matters',tags:['Couple','Road Trip','Varies','Full day','Active','Romantic']},
{t:"IKEA date",s:'Comfy furniture and Swedish meatballs',tags:['Couple','City','Under €20','Half day','Chill','Romantic']},
{t:"Take a long drive with the windows down and listen to music",s:'Insane main character vibe',tags:['Couple','Road Trip','Free','1 hour','Chill','Romantic']},
{t:"Go for a late night swim somewhere",s:'The world gets quiet after midnight',tags:['Couple','Outdoors','Nature','Free','Evening','Active','Romantic']},
{t:"Start an album together",s:'One day you will look back and say damn, we looked fine',tags:['Couple','Home','Indoors','Free','Ongoing','Lazy','Romantic']},
{t:"Go to a museum or art gallery together",s:'Best human creations all in one place, aside from you two',tags:['Couple','City','Under €10','Half day','Chill','Romantic']},
{t:"Take them somewhere from their childhood they haven't been back to",s:'The nostalgia hits in ways neither of you expects',tags:['Couple','City','Nature','Varies','Half day','Chill','Romantic']},
{t:"Read a book in nature together",s:'So peaceful and romantic',tags:['Couple','Outdoors','Nature','Free','Half day','Lazy','Romantic']},
{t:"Ask them what they've always wanted to do and do it today",s:'Be ready for anything',tags:['Couple','Varies','Full day','Active','Romantic']},
{t:"Make each other gifts with €5 only",s:'Creativity and love do the heavy lifting',tags:['Couple','Home','Indoors','Under €5','1 hour','Chill','Romantic']},
{t:"Ask each other 36 questions that make people fall in love",s:'Apparently science got involved',tags:['Couple','Home','Indoors','Free','1 hour','Lazy','Romantic']},
{t:"Sit under the stars and talk about life",s:'No rush. No pressure',tags:['Couple','Outdoors','Nature','Free','Evening','Lazy','Romantic']},
{t:"Write letters to each other",s:'Old-school romance never died',tags:['Couple','Home','Indoors','Free','30min','Lazy','Romantic']},
{t:"Slow dance to your favorite song",s:'It is very simple but very effective',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
{t:"Give each other disposable cameras for the day",s:'No deleting. No filters',tags:['Couple','Outdoors','City','Nature','Under €20','Full day','Active','Romantic']},
{t:"Create a time capsule together",s:'Open it in 5 years. Future you is curious',tags:['Couple','Home','Indoors','Under €10','1 hour','Lazy','Romantic']},
{t:"Learn something together — cooking, pottery, a language",s:"It's more fun being bad at something together",tags:['Couple','Home','Indoors','City','Under €20','Half day','Chill','Romantic']},
{t:"Revisit your oldest messages",s:'Good luck surviving the cringe',tags:['Couple','Home','Indoors','Free','30min','Lazy','Romantic']},
{t:"Buy a plant together and name it",s:'They grow up so fast',tags:['Couple','City','Under €10','1 hour','Chill','Romantic']},
{t:"Plan a trip together",s:"Cheap or expensive, 1 day or 1 month, as long as you're together",tags:['Couple','Home','Indoors','Free','1 hour','Chill','Romantic']},
{t:"Buy each other clothes or accessories you'd love to see on them",s:'Keep an open mind… and an open wallet',tags:['Couple','City','Under €50','Half day','Chill','Romantic']},
{t:"Buy a Lego set and build it together",s:"Everything is cool when you're part of the team",tags:['Couple','Home','Indoors','Under €20','Half day','Lazy','Romantic']},
{t:"Send them a voice message instead of a text",s:'Unexpectedly wholesome',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
{t:"Make them a playlist right now",s:'10 songs. No skips. Send it.',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
{t:"Text them something funny",s:'No reason needed',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
{t:"Send them a meme that made you think of them",s:'The love language of our generation',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
{t:"Plan a date night for next week — just plan it, don't tell them yet",s:'Half the fun is in the planning',tags:['Couple','Home','Indoors','Free','30min','Lazy','Romantic']},
{t:"Send them a genuine compliment out of nowhere",s:'No occasion needed. That is kind of the point.',tags:['Couple','Home','Indoors','Free','15min','Lazy','Romantic']},
]},
party:{label:'Party',emoji:'🍻',c1:'#ffb84c',c2:'#e8950a',glow:'rgba(255,184,76,.35)',ideas:[
{t:"Beer pong tournament with a real bracket",s:'Seedings, trophy, the works',tags:['Friends','Home','Indoors','Free','Evening','Active','Party']},
{t:"Spin the bottle",s:'The classic exists for a reason',tags:['Friends','Home','Indoors','Free','Evening','Lazy','Party']},
{t:"Truth or dare",s:'The dares get worse as the night goes on',tags:['Friends','Home','Indoors','Free','Evening','Lazy','Party']},
{t:"Suck and blow",s:'Eeew did you just kiss me bro?!',tags:['Friends','Home','Indoors','Free','30min','Active','Party']},
{t:"Never have I ever",s:"You will learn things about your friends you can't unlearn",tags:['Friends','Home','Indoors','Free','Evening','Lazy','Party']},
{t:"Kings cup",s:'Your rules, your chaos',tags:['Friends','Home','Indoors','Under €10','Evening','Lazy','Party']},
{t:"Beer walk",s:'Bring your friends on a long walk and bring a lot of beer — you must finish all of it',tags:['Friends','Outdoors','Under €20','Half day','Active','Party']},
{t:"Golden mile",s:'Visit all the bars you can find and have just one drink at each',tags:['Friends','City','Under €50','Evening','Active','Party']},
{t:"Invite random people to join your party",s:"You might need some liquid courage for this one…",tags:['Friends','Home','Indoors','Free','Evening','Active','Party']},
{t:"House party",s:'Throw a sick house party and call it project X',tags:['Friends','Home','Indoors','Under €50','Evening','High Energy','Party']},
{t:"Everyone brings the weirdest drink they can find — then rate them",s:'Some countries owe explanations',tags:['Friends','Home','Indoors','Under €20','Evening','Lazy','Party']},
{t:"Costume party",s:'No theme is too stupid. Dignity checked out hours ago',tags:['Friends','Home','Indoors','Under €20','Evening','Active','Party']},
{t:"White T-shirt party — everybody signs and writes messages",s:'Future nostalgia in progress',tags:['Friends','Home','Indoors','Under €10','Evening','Active','Party']},
{t:"Rooftop drinks at sunset",s:'Find the highest accessible spot in your city',tags:['Friends','City','Outdoors','Under €20','Evening','Chill','Party']},
{t:"Karaoke night at home",s:'YouTube + Bluetooth speaker + zero shame',tags:['Friends','Home','Indoors','Free','Evening','High Energy','Party']},
{t:"Shot roulette",s:'Label the glasses and spin',tags:['Friends','Home','Indoors','Under €10','Evening','Active','Party']},
{t:"Drunk Jenga — write dares on every block",s:'The tower falls, someone does something stupid',tags:['Friends','Home','Indoors','Under €10','Evening','Active','Party']},
{t:"Flip cup championship",s:'Two teams. One cup. Pure chaos',tags:['Friends','Home','Indoors','Free','Evening','High Energy','Party']},
{t:"Power hour — one shot every minute for an hour",s:'Simple math. Terrible consequences',tags:['Friends','Home','Indoors','Under €10','1 hour','Active','Party']},
{t:"Bar crawl with a theme",s:'Dress code: embarrassing. Attitude: confident',tags:['Friends','City','Under €50','Evening','High Energy','Party']},
{t:"Boat party — rent a small boat for the evening",s:'Water makes everything better',tags:['Friends','Outdoors','Expensive','Evening','Active','Party']},
{t:"Dance battle in the living room",s:'Pick your champion. Pick your song. No mercy',tags:['Friends','Home','Indoors','Free','Evening','High Energy','Party']},
{t:"Mystery cocktail competition — everyone invents a drink",s:'Then judge each others creations. Then regret them',tags:['Friends','Home','Indoors','Under €20','Evening','Chill','Party']},
{t:"Outdoor movie night with a projector or laptop",s:'Blankets, snacks, warm night',tags:['Friends','Outdoors','Under €20','Evening','Lazy','Party']},
{t:"Glow-in-the-dark party",s:'Blacklights, neon paint, chaos. You know what to do',tags:['Friends','Home','Indoors','Under €20','Evening','High Energy','Party']},
{t:"Pool party",s:"If you don't have a pool, someone you know does",tags:['Friends','Outdoors','Free','Half day','High Energy','Party']},
{t:"Host a poker night",s:'Real chips optional. Trash talk mandatory',tags:['Friends','Home','Indoors','Free','Evening','Chill','Party']},
{t:"Bonfire night",s:'Fire, stories, and someone who burns the marshmallows every single time',tags:['Friends','Outdoors','Nature','Under €20','Evening','Chill','Party']},
{t:"BBQ party",s:'Charcoal, good music, better company',tags:['Friends','Outdoors','Under €20','Half day','Active','Party']},
{t:"Beach party",s:'Sand everywhere, zero regrets',tags:['Friends','Outdoors','Nature','Under €20','Evening','High Energy','Party']},
{t:"Traffic light party",s:"Red = taken, yellow = it's complicated, green = ready to mingle. Wear accordingly",tags:['Friends','Home','Indoors','Under €10','Evening','High Energy','Party']},
{t:"Play online Skribbl.io with friends",s:'Prepare for arguments about what counts as a valid drawing',tags:['Friends','Home','Indoors','Free','1 hour','Active','Party']},
{t:"GeoGuessr battle — closest guess wins",s:'Geography knowledge not required. Confidence is.',tags:['Friends','Home','Indoors','Free','1 hour','Active','Party']},
{t:"Watch a bad movie together and roast it",s:'The worse the movie the better the night',tags:['Friends','Home','Indoors','Free','Evening','Lazy','Party']},
]},
summer:{label:'Summer',emoji:'☀️',c1:'#ff9a3c',c2:'#ff6b6b',glow:'rgba(255,154,60,.35)',ideas:[
{t:"Make a lemonade",s:'Strawberry, cucumber, watermelon — pick your poison',tags:['Solo','Couple','Friends','Home','Indoors','Free','1 hour','Chill','Summer']},
{t:"Grab water goggles and go diving",s:'Even the local pool counts',tags:['Solo','Friends','Outdoors','Free','Half day','Active','Summer']},
{t:"Chill near a lake or river",s:'Bring a towel, bring snacks, bring nothing to do',tags:['Solo','Couple','Friends','Outdoors','Nature','Free','Half day','Lazy','Summer']},
{t:"Water balloon war",s:'Fill as many as possible. Trust nobody',tags:['Friends','Family','Outdoors','Free','1 hour','High Energy','Summer']},
{t:"BBQ party",s:'Charcoal, good music, people you like',tags:['Friends','Family','Outdoors','Under €20','Half day','Active','Summer']},
{t:"Build a bonfire on the beach",s:'Stay until the fire dies or the sun comes up',tags:['Friends','Outdoors','Nature','Free','Evening','Chill','Summer']},
{t:"Night swim in a lake",s:'Slightly terrifying. Completely worth it',tags:['Friends','Outdoors','Nature','Free','Evening','Active','Scary','Summer']},
{t:"Hike to a viewpoint and have a picnic at the top",s:'The view hits different when you earned it',tags:['Solo','Couple','Friends','Outdoors','Nature','Free','Half day','Active','Summer']},
{t:"Go strawberry or fruit picking",s:'You will eat more than you take home',tags:['Couple','Friends','Family','Outdoors','Nature','Under €10','Half day','Chill','Summer']},
{t:"Hammock between two trees with a book and cold drink",s:'This is the life',tags:['Solo','Outdoors','Nature','Free','Half day','Lazy','Summer']},
{t:"Rooftop drinks at golden hour",s:'Find a rooftop. Any rooftop. Go',tags:['Couple','Friends','City','Outdoors','Under €10','Evening','Chill','Summer']},
{t:"Have breakfast outside — full spread, proper coffee",s:'No screens. Just food and morning air',tags:['Solo','Couple','Friends','Outdoors','Home','Free','1 hour','Chill','Summer']},
{t:"Drive to the coast for the day with no plan",s:'Just go. Figure it out when you get there',tags:['Couple','Friends','Outdoors','Road Trip','Under €20','Full day','Active','Summer']},
{t:"Ice cream crawl — try a flavour at three different places",s:'Rank them. Take it seriously',tags:['Couple','Friends','City','Under €10','Half day','Chill','Summer']},
{t:"Summer cocktail night on the terrace",s:"Make a proper batch, dress up slightly, pretend you're in Ibiza",tags:['Friends','Home','Outdoors','Under €10','Evening','Chill','Summer']},
{t:"Set up a projector or laptop outside and watch a movie",s:'Warm night, cold drinks, good film',tags:['Couple','Friends','Outdoors','Home','Free','Evening','Lazy','Summer']},
{t:"Farmers market morning — cook everything you bought",s:'Chaotic. Delicious. Repeat',tags:['Solo','Couple','Friends','City','Under €20','Half day','Chill','Summer']},
{t:"Float on a lake with an inflatable and do absolutely nothing",s:'Achievement unlocked: maximum chill',tags:['Solo','Couple','Outdoors','Nature','Under €10','Half day','Lazy','Summer']},
{t:"Make homemade ice cream or popsicles",s:'Mango, berry, coconut — go wild',tags:['Solo','Couple','Friends','Family','Home','Indoors','Under €10','1 hour','Chill','Summer']},
{t:"Cook a full Mediterranean spread from scratch",s:'Hummus, pita, grilled halloumi, the works',tags:['Solo','Couple','Friends','Home','Indoors','Under €20','Half day','Chill','Romantic','Summer']},
{t:"Host a tropical fruit tasting",s:'Dragonfruit, rambutan, jackfruit — whoever guesses most wins',tags:['Friends','Family','Home','Indoors','Under €20','1 hour','Chill','Summer']},
{t:"Make a summer playlist",s:'No sad songs allowed. Two hour minimum',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Summer']},
{t:"Learn a summer dish recipe",s:"Pick one refreshing thing you've never made. Master it this season",tags:['Solo','Couple','Home','Indoors','Under €20','Half day','Chill','Summer']}
]},
crazy:{label:'Crazy',emoji:'🤡',c1:'#c265ff',c2:'#8e2de2',glow:'rgba(194,101,255,.35)',ideas:[
{t:"Get a tattoo done today",s:'Would you dare a friend picking one for you?',tags:['Solo','Friends','City','Under €50','Half day','Chill','Crazy']},
{t:"Get a piercing done today",s:'Bonus points for people with no piercings yet',tags:['Solo','Friends','City','Under €20','30min','Chill','Crazy']},
{t:"Buy a ticket to another country and leave today",s:'Solo or with the gang, this will be one heck of a story',tags:['Solo','Friends','Couple','Road Trip','Under €50','Multiple days','Active','Crazy']},
{t:"Skinny dipping in the dark",s:'Katy Perry had it figured out',tags:['Friends','Couple','Outdoors','Nature','Free','Evening','Active','Crazy']},
{t:"Dye your hair",s:'If you have been thinking about it, now is the time to do it!',tags:['Solo','Friends','Home','Indoors','City','Under €20','Half day','Chill','Crazy']},
{t:"Go into a karaoke, but a friend picks a song for you",s:'Neaaar… FAaAaR…. wherEVeEeeEEER *dies*',tags:['Friends','City','Under €20','Evening','Active','Crazy']},
{t:"Give one mentally unstable friend complete control over the day",s:'Trust is about to be tested',tags:['Friends','Varies','Varies','Full day','Active','Crazy']},
{t:"Stay awake and go watch the sunrise somewhere random",s:'No sleep. No regrets',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','30min','Active','Crazy']},
{t:"Find the coldest river possible and jump in",s:'Everybody acts tough until the first toe enters',tags:['Friends','Outdoors','Nature','Free','30min','High Energy','Crazy']},
{t:"Whoever loses rock paper scissors has to do one thing everyone is scared of",s:'Character development',tags:['Friends','Varies','Varies','Active','Crazy']},
{t:"Buy an extra ticket to an event and convince a stranger to tag along",s:'Worst they can say is no',tags:['Solo','City','Under €50','Half day','Chill','Crazy']},
{t:"Wear something you've never had the confidence to wear",s:'The outfit has been waiting. The moment is now',tags:['Solo','Friends','City','Free','Full day','Chill','Crazy']},
{t:"Sleep in a completely different city tonight with no pre-booked accommodation",s:'Figure it out when you get there',tags:['Solo','Friends','City','Under €50','Multiple days','Active','Crazy']},
{t:"Go to an airport, pick a destination when you get there",s:'Now this is true uncle lore',tags:['Solo','Friends','Road Trip','Expensive','Multiple days','Active','Crazy']},
{t:"Truth or dare in public",s:'You can play with a skip, use it wisely…',tags:['Friends','City','Outdoors','Free','1 hour','Active','Crazy']},
{t:"Sneak into an event",s:'This is not a life advice. Do it at your own risk',tags:['Friends','Solo','City','Free','Half day','Active','Crazy']},
{t:"Tell someone something you've been meaning to say for a long time",s:'You know exactly who. You know exactly what',tags:['Solo','Free','30min','Chill','Crazy']},
{t:"Apply for something you think you're not ready for",s:'The rejection is also an answer. Apply anyway',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Crazy']},
{t:"Pick a discipline, whoever loses shaves their head",s:"Don't worry, hair grows back",tags:['Friends','Free','Varies','Active','Crazy']},
{t:"Introduce yourself to every single person at the next event you go to",s:'Every. Single. One',tags:['Solo','Friends','City','Varies','Evening','Active','Crazy']},
{t:"Book a one-way train ticket to anywhere and figure out the return later",s:'Get your backpacks ready, we are going… where exactly?',tags:['Solo','Friends','Road Trip','Under €20','Full day','Active','Crazy']},
{t:"Invite a celebrity to your hangout or out for a drink",s:'Worst they can say is no',tags:['Solo','Friends','City','Free','1 hour','Chill','Crazy']},
{t:"Go to a job interview for a job you don't actually want",s:'Practice lying confidently. Dress well',tags:['Solo','City','Free','Half day','Chill','Crazy']},
{t:"Spend an entire day saying yes to everything anyone asks",s:'Set absolutely no boundaries and report back',tags:['Solo','Friends','Varies','Varies','Full day','Active','Crazy']},
{t:"Do the thing you've been scared to do for months",s:'You already know what it is',tags:['Solo','Varies','Varies','Active','Crazy']},
{t:"Go busking with zero musical ability",s:'A hat, a corner, and absolutely no shame',tags:['Friends','Solo','City','Outdoors','Free','Half day','Active','Crazy']},
{t:"Text someone 'I know what you did'",s:'Then go offline for an hour',tags:['Solo','Home','Indoors','Free','15min','Lazy','Crazy']},
{t:"Text your parents something completely out of character",s:'Watch them panic in real time',tags:['Solo','Home','Indoors','Free','15min','Lazy','Crazy']},
]},
selfimprovement:{label:'Self Improvement',emoji:'📈',c1:'#4ade80',c2:'#16a34a',glow:'rgba(74,222,128,.35)',ideas:[
{t:"Learn a new instrument",s:"Your fingers will hate you for a week. Then they won't",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Self Improvement']},
{t:"Learn a foreign language",s:"The world gets 3x bigger when you can talk to more of it",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Self Improvement']},
{t:"Start meditating",s:"Your brain has been running without a restart for years",tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Go for a run",s:"The first minute is the worst. Then it's only kind of bad",tags:['Solo','Outdoors','City','Nature','Free','30min','Active','Self Improvement']},
{t:"Go to the gym",s:"The hardest rep is always the drive there",tags:['Solo','City','Under €20','1 hour','Active','Self Improvement']},
{t:"Stretch",s:"Your back has filed several formal complaints",tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Do yoga",s:"It's not just for people who own crystals",tags:['Solo','Home','Indoors','Outdoors','Free','30min','Active','Self Improvement']},
{t:"Learn 15 constellations",s:"So the next time you look up, the sky means something",tags:['Solo','Outdoors','Nature','Free','1 hour','Lazy','Self Improvement']},
{t:"Read a book",s:"Your phone has the attention span of a goldfish. Be different",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Read philosophy",s:"Warning: may cause you to question everything, including this list",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Practice stress regulation",s:"The storm doesn't stop. You just get better at sailing",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Learn to cook a new dish",s:"Pick something impressive. Serve it like you've done it 100 times",tags:['Solo','Home','Indoors','Under €20','1 hour','Active','Self Improvement']},
{t:"Rejection therapy",s:"Go get rejected on purpose today. It's cheaper than therapy",tags:['Solo','City','Free','Half day','Active','Self Improvement']},
{t:"Take a cold shower",s:"Every morning you win this fight, you win the whole day",tags:['Solo','Home','Indoors','Free','15min','Active','Self Improvement']},
{t:"Take a walk",s:"Most good ideas were born somewhere between here and there",tags:['Solo','Outdoors','City','Nature','Free','30min','Chill','Self Improvement']},
{t:"Deep breathing",s:"You've been breathing wrong your whole life. Let's fix that",tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Plant a tree",s:"You'll never sit in its shade. Do it anyway",tags:['Solo','Outdoors','Nature','Under €10','1 hour','Active','Self Improvement']},
{t:"Start a business",s:"The worst that happens is a great story. The best is everything",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy','Self Improvement']},
{t:"Do something you've been meaning to do for a while",s:"You know what it is. It's been on the list for months",tags:['Solo','Varies','Varies','Active','Self Improvement']},
{t:"Clean your room or house",s:"External chaos is just internal chaos with furniture",tags:['Solo','Home','Indoors','Free','Half day','Active','Self Improvement']},
{t:"Start or improve your skincare",s:"Your face is the first thing people see. Treat it accordingly",tags:['Solo','Home','Indoors','Under €20','15min','Lazy','Self Improvement']},
{t:"Upgrade your style",s:"You don't have to buy new things. Just wear them differently",tags:['Solo','City','Varies','Half day','Chill','Self Improvement']},
{t:"Do your hobby",s:"Not for productivity. Not for content. Just because you like it",tags:['Solo','Home','Varies','Half day','Lazy','Self Improvement']},
{t:"Start a side business",s:"One idea + one afternoon is how most of them begin",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy','Self Improvement']},
{t:"Meet new people",s:"Every interesting person you know was once a stranger",tags:['Solo','City','Free','Half day','Active','Self Improvement']},
{t:"Study for an exam",s:"Future you will be either grateful or furious. Choose which",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Learn to time manage",s:"There are actual techniques. They work. Nobody uses them",tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Self Improvement']},
{t:"Organize your tasks and write them down in a calendar",s:"Your brain is for thinking, not storage",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Start a 1-year project",s:"Pick something ambitious enough to scare you slightly",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy','Self Improvement']},
{t:"Learn basic first aid",s:"Being useful in an emergency is genuinely attractive",tags:['Solo','City','Free','Half day','Active','Self Improvement']},
{t:"Learn sign language",s:"Communication DLC. Seriously underrated",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Self Improvement']},
{t:"Fix something that's broken",s:"Become the ancestor your bloodline deserves",tags:['Solo','Home','Indoors','Varies','Half day','Active','Self Improvement']},
{t:"Learn how to identify birds, trees or mushrooms",s:"Touch grass, but professionally",tags:['Solo','Outdoors','Nature','Free','Half day','Active','Self Improvement']},
{t:"Learn chess",s:"Destroy your friends intellectually",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Self Improvement']},
{t:"Learn how to make really good coffee",s:"Barista arc incoming",tags:['Solo','Home','Indoors','Under €20','1 hour','Lazy','Self Improvement']},
{t:"Learn how to whistle with your fingers",s:"Dads have guarded this knowledge for generations",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Start journaling",s:"Your thoughts deserve better storage than 3am",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Learn speed typing",s:"Become more efficient by at least 2x",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Learn how to sew",s:"Grandma wisdom strikes again. Also saves money",tags:['Solo','Home','Indoors','Under €10','1 hour','Lazy','Self Improvement']},
{t:"Write down 30 things you want to do in life",s:"Your bucket list won't build itself",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Learn how to start a campfire",s:"Cavemen had no YouTube tutorials and they figured it out",tags:['Solo','Outdoors','Nature','Free','30min','Active','Self Improvement']},
{t:"Improve your posture",s:"Your spine has filed several formal complaints",tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Learn how to negotiate",s:"Everything is a side quest until money gets involved",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Master one signature dish",s:"Become legendary for something",tags:['Solo','Home','Indoors','Under €20','Half day','Active','Self Improvement']},
{t:"Learn how to pick a lock",s:"For legal purposes, this is a hobby",tags:['Solo','Home','Indoors','Under €20','Half day','Lazy','Self Improvement']},
{t:"Learn basic psychology",s:"Humans are weird. Including you. Especially you",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Improve your handwriting",s:"Doctors are not role models",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Learn one survival skill",s:"Knots, fire, water purification — pick one. Become suspiciously useful",tags:['Solo','Outdoors','Nature','Free','Half day','Active','Self Improvement']},
{t:"Learn how to dance",s:"Embarrassment is temporary. Moves are forever",tags:['Solo','Home','Indoors','City','Free','Half day','Active','Self Improvement']},
{t:"Learn how to edit videos",s:"Your future side hustle is watching",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy','Self Improvement']},
{t:"Learn one card trick",s:"Uncles have been abusing this power for decades",tags:['Solo','Home','Indoors','Free','30min','Lazy','Self Improvement']},
{t:"Learn morse code",s:"Useless until suddenly incredibly useful",tags:['Solo','Home','Indoors','Free','Half day','Lazy','Self Improvement']},
{t:"Learn how to change a tire",s:"This skill will save you on a dark road at midnight",tags:['Solo','Outdoors','Free','30min','Active','Self Improvement']},
{t:"Delete 3 apps you waste time on",s:'You know which ones',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Write down one thing you want to achieve this month",s:'One. Just one.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Do 10 pushups right now",s:'Just 10. That is all.',tags:['Solo','Home','Indoors','Free','15min','Active','Self Improvement']},
{t:"Drink a full glass of water right now",s:'You are probably dehydrated',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Text someone you've been meaning to text for weeks",s:'Today is the day',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Set one goal for tomorrow before you sleep",s:'One is enough',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Read one Wikipedia article about something you know nothing about",s:'Start anywhere',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Write down 3 things you're grateful for right now",s:'Sounds basic. Weirdly works.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
{t:"Go outside 10 minutes",s:'No phone. Just walk.',tags:['Solo','Outdoors','Free','15min','Chill','Self Improvement']},
{t:"Clean one small thing right now",s:'Just one. That is enough.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Self Improvement']},
]},
scary:{label:'Scary Sh*t',emoji:'🕯️',c1:'#1a1a1a',c2:'#0d0d0d',glow:'rgba(100,0,0,.35)',ideas:[
{t:"Play Ouija board",s:'What could go wrong.',tags:['Friends','Home','Indoors','Free','Evening','Chill','Scary']},
{t:"Explore abandoned buildings",s:'Bring a flashlight. Leave before dark. Probably.',tags:['Friends','Outdoors','Free','Half day','Active','Scary']},
{t:"Perform a ritual in the woods at night",s:'No instructions provided. That is kind of the point.',tags:['Friends','Outdoors','Nature','Free','Evening','High Energy','Scary']},
{t:"Play hide and seek at night in the woods",s:'The seeker has a flashlight. You do not.',tags:['Friends','Outdoors','Nature','Free','Evening','High Energy','Scary']},
{t:"Play a horror game in the dark",s:'Headphones on. Lights off. Good luck.',tags:['Solo','Friends','Home','Indoors','Free','Evening','Lazy','Scary']},
{t:"Watch a horror movie alone with headphones",s:'No pausing. No checking your phone.',tags:['Solo','Home','Indoors','Free','Evening','Lazy','Scary']},
{t:"Sit in complete darkness for 10 minutes",s:'No phone. No light. Just you and your thoughts.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Look in the mirror with dim lights for 15 minutes",s:'Your brain will start doing things.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Read real paranormal stories before bed",s:'Sleep well.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Scary']},
{t:"Listen to creepy audio recordings",s:'Whispers, analog horror, radio static — your call.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Scary']},
{t:"Imagine someone is in the room and talk to them in the dark",s:'Do not look too hard for an answer.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Walk at night with a horror soundtrack in your headphones",s:'Turns any street into a movie scene.',tags:['Solo','Outdoors','Free','30min','Active','Scary']},
{t:"Go for a zombie run",s:'An immersive app that sends zombies your way while you run.',tags:['Solo','Friends','Outdoors','Free','1 hour','High Energy','Scary']},
{t:"Walk through a cemetery at night",s:'Respectful. Creepy.',tags:['Solo','Friends','Outdoors','Free','Evening','Chill','Scary']}
]},
scary:{label:'Scary Sh*t',emoji:'🕯️',c1:'#1a1a1a',c2:'#0d0d0d',glow:'rgba(100,0,0,.35)',ideas:[
{t:"Play Ouija board",s:'What could go wrong.',tags:['Friends','Home','Indoors','Free','Evening','Chill','Scary']},
{t:"Explore abandoned buildings",s:'Bring a flashlight. Leave before dark. Probably.',tags:['Friends','Outdoors','Free','Half day','Active','Scary']},
{t:"Perform a ritual in the woods at night",s:'No instructions provided. That is kind of the point.',tags:['Friends','Outdoors','Nature','Free','Evening','High Energy','Scary']},
{t:"Play hide and seek at night in the woods",s:'The seeker has a flashlight. You do not.',tags:['Friends','Outdoors','Nature','Free','Evening','High Energy','Scary']},
{t:"Play a horror game in the dark",s:'Headphones on. Lights off. Good luck.',tags:['Solo','Friends','Home','Indoors','Free','Evening','Lazy','Scary']},
{t:"Watch a horror movie alone with headphones",s:'No pausing. No checking your phone.',tags:['Solo','Home','Indoors','Free','Evening','Lazy','Scary']},
{t:"Sit in complete darkness for 10 minutes",s:'No phone. No light. Just you and your thoughts.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Look in the mirror with dim lights for 15 minutes",s:'Your brain will start doing things.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Read real paranormal stories before bed",s:'Sleep well.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Scary']},
{t:"Listen to creepy audio recordings",s:'Whispers, analog horror, radio static — your call.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Scary']},
{t:"Imagine someone is in the room and talk to them in the dark",s:'Do not look too hard for an answer.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Scary']},
{t:"Walk at night with a horror soundtrack in your headphones",s:'Turns any street into a movie scene.',tags:['Solo','Outdoors','Free','30min','Active','Scary']},
{t:"Go for a zombie run",s:'An immersive app that sends zombies your way while you run.',tags:['Solo','Friends','Outdoors','Free','1 hour','High Energy','Scary']},
{t:"Walk through a cemetery at night",s:'Respectful. Creepy.',tags:['Solo','Friends','Outdoors','Free','Evening','Chill','Scary']}
]}
,
nostalgic:{label:'Nostalgic',emoji:'📼',c1:'#a8a8b3',c2:'#6b6b7a',glow:'rgba(200,200,210,.35)',ideas:[
{t:"Rewatch your favourite childhood cartoon",s:'Some hold up. Some really do not.',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Nostalgic']},
{t:"Listen to the first album you ever loved",s:'Start to finish. No skipping.',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Nostalgic']},
{t:"Go through your old photos",s:'You will find something that hits harder than expected.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Nostalgic']},
{t:"Play a video game you used to play as a kid",s:'Muscle memory never really leaves.',tags:['Solo','Friends','Home','Indoors','Free','1 hour','Lazy','Nostalgic']},
{t:"Eat something you haven't had since childhood",s:'It will taste exactly the same. Or completely different.',tags:['Solo','Home','Indoors','Under €10','30min','Lazy','Nostalgic']},
{t:"Look up places you have been a long time ago on Google Maps",s:'See how much has changed. Or how little.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Nostalgic']},
{t:"Text someone you lost touch with",s:'They are probably thinking about you too.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Nostalgic']},
{t:"Find your old drawings or school projects",s:'You were either a genius or a disaster. Possibly both.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Nostalgic']},
{t:"Watch old home videos",s:'Prepare yourself.',tags:['Solo','Family','Home','Indoors','Free','30min','Lazy','Nostalgic']},
{t:"Look up what was #1 on the charts when you were a kid",s:'You will remember every word.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Nostalgic']},
{t:"Play games you played as kids",s:'Hide and seek hits different as an adult.',tags:['Friends','Family','Outdoors','Free','1 hour','Active','Nostalgic']},
{t:"Cook a meal your grandma used to make",s:'Even if it does not taste the same, it is close enough.',tags:['Solo','Couple','Home','Indoors','Under €20','Half day','Chill','Nostalgic']},
{t:"Show each other your childhood photos",s:'No context needed. Just laugh.',tags:['Friends','Family','Home','Indoors','Free','30min','Lazy','Nostalgic']},
{t:"Watch your favourite cartoons from when you were growing up",s:'Some episodes you will remember frame by frame.',tags:['Solo','Friends','Home','Indoors','Free','1 hour','Lazy','Nostalgic']},
{t:"Share your core childhood memories",s:'The ones that made you who you are.',tags:['Friends','Family','Home','Indoors','Free','Evening','Chill','Nostalgic']},
{t:"Go through your oldest messages with someone",s:'You were a different person. Kind of.',tags:['Solo','Home','Indoors','Free','30min','Lazy','Nostalgic']},
{t:"Find your first ever social media post",s:'Cringe is a form of growth.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Nostalgic']},
{t:"Look up what was trending the year you started high school",s:'It was a different world.',tags:['Solo','Home','Indoors','Free','15min','Lazy','Nostalgic']},
{t:"Listen to your favourite songs from when you were growing up",s:'Play the whole playlist. No shuffle.',tags:['Solo','Home','Indoors','Free','1 hour','Lazy','Nostalgic']}
]}
};