const CATS = {
adventure:{label:'Adventure',emoji:'🏕️',c1:'#ff8a4c',c2:'#d4622a',glow:'rgba(255,138,76,.35)',ideas:[
{t:"Get off at a train stop you've never heard of and explore it",s:"Somebody's favourite café is probably hiding there",tags:['Solo','Friends','Outdoors','City','Nature','Free','Half day','Chill']},
{t:"Find the place with the weirdest name within 50km and go see it",s:"There's only one way to find out why it's called that",tags:['Solo','Friends','Road Trip','Under €10','Full day','Chill']},
{t:"Jump into a nearby lake or sea",s:"Your nervous system is about to receive important news",tags:['Friends','Couple','Outdoors','Nature','Free','30min','High Energy']},
{t:"Zoom out on Google Maps and pick somewhere random to go today",s:"Today's destination has been selected by fate",tags:['Friends','Solo','Road Trip','Under €10','Full day','Active']},
{t:"Go horseback riding",s:"Yeah I'm gonna take my horse to the…",tags:['Friends','Couple','Outdoors','Nature','Under €50','Half day','Active']},
{t:"Sleep in a tent",s:'Hotels are nice, but bears make memories',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Chill']},
{t:"Try climbing or bouldering",s:"Don't look down… don't look down…",tags:['Friends','Solo','Outdoors','Nature','Under €20','Half day','High Energy']},
{t:"Go cliff jumping",s:'Brain says AAH, you say AAAAAAH',tags:['Friends','Outdoors','Nature','Free','Half day','High Energy']},
{t:"Find the scariest ride in the amusement park",s:'Who will scream the loudest?',tags:['Friends','Family','City','Under €50','Full day','High Energy']},
{t:"Try scuba diving",s:'ATLANTIS HERE WE COME',tags:['Friends','Couple','Outdoors','Nature','Under €50','Half day','Active']},
{t:"Take a helicopter ride",s:'Expensive? Yes. Once in a lifetime? Also yes',tags:['Friends','Couple','Nature','City','Expensive','Half day','Chill']},
{t:"You could go fishing",s:'The supermarket has made us soft',tags:['Friends','Solo','Outdoors','Nature','Free','Full day','Lazy']},
{t:"Rent a boat for a day",s:'Getting stranded in the middle of the sea with friends?! FUN',tags:['Friends','Outdoors','Nature','Under €50','Full day','Chill']},
{t:"Try surfing",s:'Radical…',tags:['Friends','Solo','Outdoors','Nature','Under €50','Full day','High Energy']},
{t:"Sleep somewhere weird",s:'Treehouse. Lighthouse. Castle. Go crazy with it',tags:['Friends','Couple','Outdoors','Nature','Under €50','Multiple days','Chill']},
{t:"Climb a mountain",s:"Preferably don't start with Everest",tags:['Friends','Solo','Outdoors','Nature','Free','Full day','High Energy']},
{t:"Hike through some pretty trails",s:'Pretty views, delicious snacks, healthy choices',tags:['Friends','Solo','Family','Outdoors','Nature','Free','Full day','Active']},
{t:"Go night swimming",s:"The sea gets way bigger when you can't see the bottom",tags:['Friends','Couple','Outdoors','Nature','Free','1 hour','Active']},
{t:"Board the next train or bus without checking where it's going",s:'Future you can figure it out',tags:['Solo','Friends','City','Under €10','Full day','Chill']},
{t:"Drive somewhere with zero light pollution",s:'Stars are kind of ridiculous without street lamps competing',tags:['Friends','Couple','Outdoors','Nature','Under €10','Evening','Chill']},
{t:"Buy the cheapest ticket to another country and spend a day there",s:'Tristan da Cunha people will not like this one',tags:['Friends','Solo','Couple','Road Trip','Under €50','Multiple days','Active']},
{t:"Get on a train with no return ticket",s:'Future you seems like a capable guy',tags:['Solo','Friends','Road Trip','Under €20','Multiple days','Active']},
{t:"Go skydiving",s:"Momma didn't raise no b****!",tags:['Friends','Solo','Outdoors','Nature','Expensive','Half day','High Energy']},
{t:"Find the coldest river nearby and jump in",s:'Everyone acts tough until the first toe enters the water',tags:['Friends','Outdoors','Nature','Free','30min','High Energy']},
{t:"Find a cave and go explore it",s:'Or actually take a tour guide? Just saying…',tags:['Friends','Solo','Outdoors','Nature','Under €20','Half day','Active']},
{t:"Spend a night in a mountain hut",s:'What was that sound?',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Active']},
{t:"Rent jet skis",s:'Childhood dreams and poor financial decisions finally meet',tags:['Friends','Couple','Outdoors','Nature','Expensive','Half day','High Energy']},
{t:"Sleep in your car somewhere beautiful",s:'Five-star view, one-star mattress',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','Multiple days','Chill']},
{t:"Wake up early to see the sunrise",s:"Don't give me that look…",tags:['Solo','Couple','Friends','Outdoors','Nature','Free','30min','Chill']},
{t:"Make a campfire and cook food on it",s:'Bonus points for guitar players',tags:['Friends','Family','Outdoors','Nature','Under €10','Evening','Chill']},
{t:"Camp in the rain",s:'Cozy, nature and hot tea — what more do you need?',tags:['Friends','Couple','Outdoors','Nature','Under €20','Multiple days','Chill']},
{t:"Sleep outside with no tent",s:'It looked easier watching Bear Grylls do it',tags:['Friends','Outdoors','Nature','Free','Multiple days','Active']},
{t:"Explore abandoned buildings nearby",s:'It was the wind bro, I swear',tags:['Friends','Outdoors','City','Nature','Free','Half day','Active']},
{t:"Ask a stranger for a hidden gem",s:'The real adventure is the friends we made along the way',tags:['Solo','Friends','City','Free','Half day','Chill']},
{t:"Try paragliding",s:'The ground looks fake from up here',tags:['Friends','Couple','Outdoors','Nature','Expensive','Half day','High Energy']},
{t:"Go kayaking or canoeing",s:'Arms will hurt. Worth it',tags:['Friends','Couple','Solo','Outdoors','Nature','Under €20','Half day','Active']},
{t:"Try a via ferrata",s:'Like climbing, but with a safety wire and a whole lot of trust',tags:['Friends','Solo','Outdoors','Nature','Under €20','Full day','High Energy']},
{t:"Do a night hike with headlamps",s:'Who dares exploring the woods like this?',tags:['Friends','Outdoors','Nature','Free','Evening','Active']},
{t:"Try rafting with your friends",s:'The river has opinions. Respect them',tags:['Friends','Outdoors','Nature','Under €50','Half day','High Energy']},
{t:"Find a waterfall and swim in it",s:"Nature's original infinity pool",tags:['Friends','Couple','Outdoors','Nature','Free','Full day','Active']},
{t:"Go mountain biking downhill",s:'Gravity does half the work. Fear does the other half',tags:['Friends','Solo','Outdoors','Nature','Under €50','Half day','High Energy']},
{t:"Try an outdoor survival challenge",s:'2-3 days no phone. Now what?',tags:['Friends','Solo','Outdoors','Nature','Under €50','Multiple days','High Energy']},
{t:"Go bungee jumping",s:'Your body will file a complaint. Sign it anyway',tags:['Friends','Solo','Outdoors','Nature','Expensive','Half day','High Energy']},
{t:"Find a local legend or folklore location and visit it",s:'Every town has a story. Go find yours',tags:['Friends','Solo','Outdoors','Nature','City','Free','Half day','Chill']},
{t:"Rent motorbikes or bikes for the day and explore",s:'Wind in your hair, poor decisions ahead',tags:['Friends','Couple','Road Trip','Under €50','Full day','Active']},
{t:"Try coasteering",s:'Jumping off rocks into the sea like nature intended',tags:['Friends','Outdoors','Nature','Under €20','Half day','High Energy']},
{t:"Build a raft and actually test it",s:'Minecraft logic meets real consequences',tags:['Friends','Outdoors','Nature','Under €10','Full day','Active']},
{t:"Do something you've always been too scared to do",s:'You already know what it is',tags:['Solo','Friends','Varies','Varies','High Energy']},
{t:"Seek for geodes or other natural treasures",s:'The earth has been hiding things. Time to find them',tags:['Friends','Family','Solo','Outdoors','Nature','Free','Half day','Active']}
]},
chill:{label:'Chill',emoji:'☁️',c1:'#5fd4c4',c2:'#2a9d8f',glow:'rgba(95,212,196,.35)',ideas:[
{t:"Find a pretty spot and listen to music",s:"Sometimes that's enough",tags:['Solo','Couple','Outdoors','Nature','City','Free','1 hour','Lazy']},
{t:"Read a book outside",s:'Books somehow hit different in nature',tags:['Solo','Outdoors','Nature','Free','Half day','Lazy']},
{t:"Make the best hot chocolate you possibly can",s:"We're going for Michelin stars today",tags:['Solo','Friends','Home','Indoors','Under €5','30min','Lazy']},
{t:"Try meditating for 10 minutes",s:'Your brain could use a coffee break',tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Stretch for 15 minutes",s:'Your back has been sending complaints',tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Watch the sunset and talk about life",s:'In all the chaos, a blink of calm',tags:['Couple','Friends','Outdoors','Nature','Free','1 hour','Lazy']},
{t:"Go for a walk with no destination",s:"It's to appreciate the details around you",tags:['Solo','Couple','Outdoors','City','Nature','Free','1 hour','Chill']},
{t:"Sit around a campfire",s:"It's kind of hypnotic",tags:['Friends','Couple','Outdoors','Nature','Under €10','Evening','Lazy']},
{t:"Pet an animal and forget about life for a bit",s:'They seem to have it figured out',tags:['Solo','Couple','Outdoors','Nature','City','Free','30min','Lazy']},
{t:"Find some bugs outside",s:'There is so much going on all around us',tags:['Solo','Family','Outdoors','Nature','Free','30min','Lazy']},
{t:"Make your own jewellery",s:'Just find a rock, shape it, string through it — easier than it seems',tags:['Solo','Friends','Home','Indoors','Under €5','Half day','Lazy']},
{t:"Visit a cozy café and order some tea or coffee",s:'Bring a book, a friend, or just stare at life happening around you',tags:['Solo','Couple','City','Under €5','Half day','Lazy']},
{t:"Lie in the grass and watch the clouds",s:'Cloud engineers deserve recognition',tags:['Solo','Couple','Outdoors','Nature','Free','30min','Lazy']},
{t:"Make tea and just stare out the window",s:'Grandma energy. Embrace it',tags:['Solo','Home','Indoors','Under €5','15min','Lazy']},
{t:"Take the longest shower known to mankind",s:'Ideas have been born here',tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Light a scented candle and turn off the lights",s:'Combine that with a movie, snacks and a warm drink',tags:['Solo','Couple','Home','Indoors','Under €10','Evening','Lazy']},
{t:"Buy a plant",s:"Congratulations, you're responsible for a life now",tags:['Solo','Couple','City','Under €10','1 hour','Lazy']},
{t:"Sit under a tree",s:'People used to call this an afternoon',tags:['Solo','Couple','Outdoors','Nature','Free','Half day','Lazy']},
{t:"Listen to an album from start to finish",s:'No skipping. Trust the artist',tags:['Solo','Home','Indoors','Free','1 hour','Lazy']},
{t:"Buy an analog camera and take some photos",s:"Every photo counts, that's what makes it special",tags:['Solo','Friends','Couple','Outdoors','City','Nature','Under €20','Half day','Chill']},
{t:"Bake something",s:'Your house deserves to smell amazing',tags:['Solo','Friends','Home','Indoors','Under €10','Half day','Chill']},
{t:"Eat breakfast outside",s:'The birds have been doing this forever',tags:['Solo','Couple','Outdoors','Nature','Under €10','30min','Lazy']},
{t:"Do a puzzle together",s:'Your grandparents knew what they were doing',tags:['Friends','Couple','Family','Home','Indoors','Under €10','Half day','Lazy']},
{t:"Make something out of clay",s:'Elementary school vibes',tags:['Solo','Friends','Home','Indoors','Under €10','Half day','Lazy']},
{t:"Call someone you haven't talked to in a while",s:'Do not overthink. Just call them',tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Maybe you just need a nap",s:'No seriously',tags:['Solo','Home','Indoors','Free','1 hour','Lazy']},
{t:"Write a postcard to someone",s:'Very meaningful and very underrated',tags:['Solo','Home','Indoors','Under €5','30min','Lazy']},
{t:"Movie night",s:'Popcorn, friends and a great movie',tags:['Friends','Couple','Home','Indoors','Under €10','Evening','Lazy']},
{t:"Stargaze at a spot with no light pollution",s:'This is peak chill',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','Evening','Lazy']},
{t:"Buy some drinks and find a chill spot",s:'An evergreen combo',tags:['Friends','Couple','Outdoors','Nature','City','Under €10','Evening','Lazy']},
{t:"Look through an old photo album",s:'Ah, the nostalgia',tags:['Solo','Family','Home','Indoors','Free','30min','Lazy']},
{t:"Visit a bakery early in the morning",s:'Something about the smell just fixes people',tags:['Solo','Couple','City','Under €5','30min','Lazy']},
{t:"Start a tiny herb garden",s:"Congratulations. You're basically a medieval healer now",tags:['Solo','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Rearrange your room or buy new decorations",s:'Sometimes your room needs character development too',tags:['Solo','Home','Indoors','Under €20','Half day','Chill']},
{t:"Put on headphones and listen to your favourite songs with your eyes closed",s:'Let the music take you somewhere else',tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Order way too much food and regret nothing",s:"Leftovers are tomorrow's problem",tags:['Friends','Couple','Home','Indoors','Under €20','Evening','Lazy']},
{t:"Go for a late night drive",s:'No destination. Just vibes',tags:['Friends','Couple','Solo','Road Trip','Under €10','Evening','Lazy']},
{t:"Play board games",s:'They are actually still very fun',tags:['Friends','Family','Home','Indoors','Free','Half day','Lazy']},
{t:"Buy random snacks and rate them",s:'Democracy but for snacks',tags:['Friends','Couple','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Retro games night",s:'8-bit sounds and old memories',tags:['Friends','Couple','Home','Indoors','Free','Evening','Lazy']},
{t:"Go for a walk and talk about life",s:'Therapy, but cheaper',tags:['Friends','Couple','Outdoors','City','Nature','Free','1 hour','Chill']},
{t:"Play some video games with a friend",s:'Core childhood memories unlocked',tags:['Friends','Home','Indoors','Free','Half day','Lazy']},
{t:"Find a hammock spot and just exist for a while",s:'Horizontal is a valid life choice',tags:['Solo','Couple','Outdoors','Nature','Free','Half day','Lazy']},
{t:"Cook a proper meal from scratch with no shortcuts",s:'Turns out your phone has recipes, not just doom',tags:['Solo','Couple','Home','Indoors','Under €20','Half day','Chill']},
{t:"Watch the rain from somewhere warm",s:'One of those simple things that just works',tags:['Solo','Couple','Home','Indoors','Free','30min','Lazy']},
{t:"Write down everything that's on your mind",s:'No structure, no goal. Just get it out',tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Sit in a park and just people-watch",s:'Humans are fascinating when you stop being one of them',tags:['Solo','Couple','Outdoors','City','Free','1 hour','Lazy']},
{t:"Make a playlist for a specific feeling",s:'Not a vibe. A very specific feeling at 11pm on a Tuesday',tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Find a field and just lie in it",s:'No agenda. No phone. Just sky',tags:['Solo','Couple','Outdoors','Nature','Free','1 hour','Lazy']},
{t:"Do absolutely nothing and be okay with it",s:'Revolutionary concept',tags:['Solo','Home','Indoors','Free','Half day','Lazy']}
]},
fun:{label:'Fun',emoji:'🎉',c1:'#ffd23f',c2:'#f0a500',glow:'rgba(255,210,63,.35)',ideas:[
{t:"Go to a karaoke bar",s:"The ones who say they can't sing always go the hardest",tags:['Friends','City','Under €20','Evening','Active']},
{t:"Go to an escape room",s:'If there are 4 you can pick a hidden impostor to sabotage your escape!',tags:['Friends','Couple','City','Under €20','1 hour','Chill']},
{t:"Host a cooking competition at home",s:'Gordon Ramsay energy, student budget ingredients',tags:['Friends','Home','Indoors','Under €20','Half day','Active']},
{t:"Do a pub quiz",s:'That one friend who knows random facts finally gets to shine',tags:['Friends','City','Under €10','Evening','Lazy']},
{t:"Play mini golf",s:'Surprisingly competitive. Someone will take it too seriously',tags:['Friends','Couple','Family','City','Under €10','1 hour','Chill']},
{t:"Play beer pong",s:'The rules are simple. The consequences are not',tags:['Friends','Home','Indoors','Under €10','Evening','Active']},
{t:"Play truth or dare",s:'The questions can be pretty bad',tags:['Friends','Home','Indoors','Free','Evening','Chill']},
{t:"Host a campfire night and cook some food",s:'Bonus points for guitar players',tags:['Friends','Family','Outdoors','Nature','Under €10','Evening','Chill']},
{t:"Race with shopping carts",s:'We were just borrowing them!',tags:['Friends','City','Free','30min','High Energy']},
{t:"Host a PowerPoint night",s:'The topics can be as deluded as you want',tags:['Friends','Home','Indoors','Free','Evening','Lazy']},
{t:"Mouth filled with water — you laugh you lose",s:'Sit face to face and die laughing',tags:['Friends','Couple','Home','Indoors','Free','30min','Lazy']},
{t:"Make your own go-karts and race with them",s:"It's basically human Mario Kart",tags:['Friends','Outdoors','Under €20','Half day','High Energy']},
{t:"You have 15 minutes — find the weirdest thing for under €10",s:'No rules. No limits. No refunds',tags:['Friends','City','Under €10','30min','Active']},
{t:"Blindfold taste test",s:'Coke vs Pepsi wars begin today',tags:['Friends','Couple','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Water balloon war",s:'The Geneva Convention says nothing about this',tags:['Friends','Family','Outdoors','Under €10','1 hour','High Energy']},
{t:"Paintball",s:'Everybody becomes John Wick for an hour and gets a lot of bruises',tags:['Friends','Outdoors','City','Nature','Under €50','Half day','High Energy']},
{t:"Theme night",s:'Cowboys? Mafia? Hawaiian shirts? Sky is the limit!',tags:['Friends','Home','Indoors','Under €20','Evening','Chill']},
{t:"Build paper airplanes and compete",s:'Aerospace engineers start somewhere',tags:['Friends','Family','Home','Indoors','Outdoors','Free','1 hour','Lazy']},
{t:"Board game night",s:'Friendships are temporary. Victory is forever',tags:['Friends','Family','Home','Indoors','Under €10','Evening','Lazy']},
{t:"Build something stupid together",s:'Maximum creativity. Minimum engineering',tags:['Friends','Home','Indoors','Under €10','Half day','Active']},
{t:"Decide for each other what to wear and actually wear it in public",s:'Also a great punishment for losing a challenge',tags:['Friends','City','Free','Half day','Chill']},
{t:"Host a cocktail night",s:'The hardest part is finding the ingredients',tags:['Friends','Home','Indoors','Under €20','Evening','Chill']},
{t:"Everybody brings one mystery ingredient and you cook with all of them",s:'No veto rights. No complaints',tags:['Friends','Home','Indoors','Under €20','Half day','Active']},
{t:"Go to the arcade",s:'Your wallet is weaker than your inner child',tags:['Friends','Couple','Family','City','Under €20','Half day','Active']},
{t:"Everyone gets one random object and must sell it within an hour",s:'Shark Tank energy',tags:['Friends','Home','Indoors','City','Free','1 hour','Active']},
{t:"Rock paper scissors — losers get a challenge picked by everyone else",s:'This is how gambling addictions start',tags:['Friends','Home','Indoors','Free','30min','Lazy']},
{t:"Find a free event happening in your city and crash it",s:"They're everywhere and nobody checks",tags:['Friends','Solo','City','Free','Half day','Chill']},
{t:"Everybody orders food for the person on their left",s:'Trust issues included',tags:['Friends','Home','Indoors','City','Under €20','Half day','Lazy']},
{t:"Buy drinks and snacks you've never tried and rank them",s:'Some countries owe apologies',tags:['Friends','Couple','Home','Indoors','Under €20','1 hour','Lazy']},
{t:"Have a mukbang at a fast food restaurant",s:'Or bring the food to a spot that actually slaps',tags:['Friends','City','Nature','Under €20','Half day','Lazy']},
{t:"Go to a thrift shop and find some cool clothes",s:'Grandmas and grandpas had some serious drip',tags:['Friends','Couple','City','Under €10','Half day','Chill']},
{t:"Be fashion designers for each other",s:'You can actually try to give good advice here',tags:['Friends','Couple','Home','Indoors','Free','1 hour','Lazy']},
{t:"Take a day trip — pick any location",s:'No overthinking. Just go',tags:['Friends','Couple','Road Trip','Under €20','Full day','Chill']},
{t:"Explore a cool place with bikes only",s:'Childhood memories here we come',tags:['Friends','Couple','Family','Outdoors','City','Nature','Free','Half day','Active']},
{t:"Play hide and seek but the seeker has water balloons",s:'Full of adrenaline, full of laughs',tags:['Friends','Family','Outdoors','Under €10','1 hour','High Energy']},
{t:"Play Among Us IRL",s:'Spread tasks across the house, murderer kills by tapping you twice',tags:['Friends','Home','Indoors','Free','1 hour','Active']},
{t:"Have a picnic and bring some card games",s:'Simple and effective',tags:['Friends','Couple','Family','Outdoors','Nature','Under €10','Half day','Lazy']},
{t:"Have a BBQ party",s:'Great food and even greater friends',tags:['Friends','Family','Outdoors','Under €20','Half day','Chill']},
{t:"Everybody gets €5 and buys a mystery gift for someone else",s:'The thought counts. Allegedly',tags:['Friends','City','Under €10','Half day','Chill']},
{t:"Seek for geodes or other natural treasures",s:'The earth has been hiding things. Time to find them',tags:['Friends','Family','Solo','Outdoors','Nature','Free','Half day','Active']},
{t:"Drive somewhere absurdly far for one specific food item",s:'Two hours for nuggets? Absolutely',tags:['Friends','Couple','Road Trip','Under €20','Full day','Chill']},
{t:"Hide 100 tiny objects around a friend's house without them knowing",s:'Months later they will still be finding them',tags:['Friends','Home','Indoors','Free','1 hour','Lazy']}
]},
romantic:{label:'Romantic',emoji:'❤️',c1:'#ff6b9d',c2:'#e0457a',glow:'rgba(255,107,157,.35)',ideas:[
{t:"Massage each other",s:'No special skills needed, just good intentions',tags:['Couple','Home','Indoors','Free','30min','Lazy']},
{t:"Ice cream date",s:'Simple, sweet, never fails',tags:['Couple','City','Under €10','1 hour','Chill']},
{t:"Grab a picnic blanket and find a romantic spot to chill",s:'Snacks, sunshine, and zero plans',tags:['Couple','Outdoors','Nature','Under €10','Half day','Lazy']},
{t:"Make a necklace or bracelet for your SO",s:'Handmade beats store-bought every time',tags:['Couple','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Bake them something",s:'The smell of effort is underrated',tags:['Couple','Home','Indoors','Under €10','Half day','Chill']},
{t:"Take them on a surprise date",s:'Plan everything. Reveal nothing',tags:['Couple','City','Varies','Half day','Chill']},
{t:"Learn constellations and watch the stars together",s:'Suddenly the sky means something',tags:['Couple','Outdoors','Nature','Free','Evening','Lazy']},
{t:"Art date — draw, paint or work with clay",s:"You'll both be bad at it. That's the fun part",tags:['Couple','Home','Indoors','City','Under €20','Half day','Chill']},
{t:"Take them where you first met and reminisce",s:'Full circle moments hit different',tags:['Couple','City','Free','Half day','Chill']},
{t:"Surprise them with a small gift today",s:"No occasion needed. That's what makes it good",tags:['Couple','City','Under €10','30min','Chill']},
{t:"Take them to their favorite restaurant",s:'Sometimes the classics just work',tags:['Couple','City','Under €50','Half day','Chill']},
{t:"Cook a full meal together from scratch",s:'Pick a cuisine neither of you has tried before',tags:['Couple','Home','Indoors','Under €20','Half day','Chill']},
{t:"Recreate your first date as closely as possible",s:'Same place, same order, same energy',tags:['Couple','City','Varies','Half day','Chill']},
{t:"Find the highest point near your city and watch the sunset",s:'The view is better with someone next to you',tags:['Couple','Outdoors','Nature','City','Free','Evening','Chill']},
{t:"Pick them flowers and make a bouquet",s:'Wildflowers count. Effort is the gift',tags:['Couple','Outdoors','Nature','Free','30min','Chill']},
{t:"Go somewhere nice with bicycles",s:'Getting lost together is a love language',tags:['Couple','Outdoors','City','Nature','Free','Half day','Active']},
{t:"Read to each other",s:"Pick a book. Take turns. It's incredibly intimate for no obvious reason",tags:['Couple','Home','Indoors','Free','1 hour','Lazy']},
{t:"Do a spa night at home",s:'Candles, face masks, the whole thing. No irony',tags:['Couple','Home','Indoors','Under €20','Evening','Lazy']},
{t:"Have a lazy date",s:'Watch a movie, order your favorite food and chill',tags:['Couple','Home','Indoors','Under €20','Evening','Lazy']},
{t:"Dress up and go to a jazz bar",s:'Smooth jazz for a smooth duo',tags:['Couple','City','Under €20','Evening','Chill']},
{t:"Take them on a mystery trip",s:'Could be anything. The anticipation is what matters',tags:['Couple','Road Trip','Varies','Full day','Active']},
{t:"IKEA date",s:'Comfy furniture and Swedish meatballs',tags:['Couple','City','Under €20','Half day','Chill']},
{t:"Take a long drive with the windows down and listen to music",s:'Insane main character vibe',tags:['Couple','Road Trip','Free','1 hour','Chill']},
{t:"Go for a late night swim somewhere",s:'The world gets quiet after midnight',tags:['Couple','Outdoors','Nature','Free','Evening','Active']},
{t:"Start an album together",s:'One day you will look back and say damn, we looked fine',tags:['Couple','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Go to a museum or art gallery together",s:'Best human creations all in one place, aside from you two',tags:['Couple','City','Under €10','Half day','Chill']},
{t:"Take them somewhere from their childhood they haven't been back to",s:'The nostalgia hits in ways neither of you expects',tags:['Couple','City','Nature','Varies','Half day','Chill']},
{t:"Read a book in nature together",s:'So peaceful and romantic',tags:['Couple','Outdoors','Nature','Free','Half day','Lazy']},
{t:"Ask them what they've always wanted to do and do it today",s:'Be ready for anything',tags:['Couple','Varies','Full day','Active']},
{t:"Make each other gifts with €5 only",s:'Creativity and love do the heavy lifting',tags:['Couple','Home','Indoors','Under €5','1 hour','Chill']},
{t:"Ask each other 36 questions that make people fall in love",s:'Apparently science got involved',tags:['Couple','Home','Indoors','Free','1 hour','Lazy']},
{t:"Sit under the stars and talk about life",s:'No rush. No pressure',tags:['Couple','Outdoors','Nature','Free','Evening','Lazy']},
{t:"Write letters to each other",s:'Old-school romance never died',tags:['Couple','Home','Indoors','Free','30min','Lazy']},
{t:"Slow dance to your favorite song",s:'It is very simple but very effective',tags:['Couple','Home','Indoors','Free','15min','Lazy']},
{t:"Give each other disposable cameras for the day",s:'No deleting. No filters',tags:['Couple','Outdoors','City','Nature','Under €20','Full day','Active']},
{t:"Create a time capsule together",s:'Open it in 5 years. Future you is curious',tags:['Couple','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Learn something together — cooking, pottery, a language",s:"It's more fun being bad at something together",tags:['Couple','Home','Indoors','City','Under €20','Half day','Chill']},
{t:"Revisit your oldest messages",s:'Good luck surviving the cringe',tags:['Couple','Home','Indoors','Free','30min','Lazy']},
{t:"Buy a plant together and name it",s:'They grow up so fast',tags:['Couple','City','Under €10','1 hour','Chill']},
{t:"Plan a trip together",s:"Cheap or expensive, 1 day or 1 month, as long as you're together",tags:['Couple','Home','Indoors','Free','1 hour','Chill']},
{t:"Buy each other clothes or accessories you'd love to see on them",s:'Keep an open mind… and an open wallet',tags:['Couple','City','Under €50','Half day','Chill']},
{t:"Buy a Lego set and build it together",s:"Everything is cool when you're part of the team",tags:['Couple','Home','Indoors','Under €20','Half day','Lazy']}
]},
party:{label:'Party',emoji:'🍻',c1:'#ffb84c',c2:'#e8950a',glow:'rgba(255,184,76,.35)',ideas:[
{t:"Beer pong tournament with a real bracket",s:'Seedings, trophy, the works',tags:['Friends','Home','Indoors','Free','Evening','Active']},
{t:"Spin the bottle",s:'The classic exists for a reason',tags:['Friends','Home','Indoors','Free','Evening','Lazy']},
{t:"Truth or dare",s:'The dares get worse as the night goes on',tags:['Friends','Home','Indoors','Free','Evening','Lazy']},
{t:"Suck and blow",s:'Eeew did you just kiss me bro?!',tags:['Friends','Home','Indoors','Free','30min','Active']},
{t:"Never have I ever",s:"You will learn things about your friends you can't unlearn",tags:['Friends','Home','Indoors','Free','Evening','Lazy']},
{t:"Kings cup",s:'Your rules, your chaos',tags:['Friends','Home','Indoors','Under €10','Evening','Lazy']},
{t:"Beer walk",s:'Bring your friends on a long walk and bring a lot of beer — you must finish all of it',tags:['Friends','Outdoors','Under €20','Half day','Active']},
{t:"Golden mile",s:'Visit all the bars you can find and have just one drink at each',tags:['Friends','City','Under €50','Evening','Active']},
{t:"Invite random people to join your party",s:"You might need some liquid courage for this one…",tags:['Friends','Home','Indoors','Free','Evening','Active']},
{t:"House party",s:'Throw a sick house party and call it project X',tags:['Friends','Home','Indoors','Under €50','Evening','High Energy']},
{t:"Everyone brings the weirdest drink they can find — then rate them",s:'Some countries owe explanations',tags:['Friends','Home','Indoors','Under €20','Evening','Lazy']},
{t:"Costume party",s:'No theme is too stupid. Dignity checked out hours ago',tags:['Friends','Home','Indoors','Under €20','Evening','Active']},
{t:"White T-shirt party — everybody signs and writes messages",s:'Future nostalgia in progress',tags:['Friends','Home','Indoors','Under €10','Evening','Active']}
]},
crazy:{label:'Crazy',emoji:'🤡',c1:'#c265ff',c2:'#8e2de2',glow:'rgba(194,101,255,.35)',ideas:[
{t:"Get a tattoo done today",s:'Would you dare a friend picking one for you?',tags:['Solo','Friends','City','Under €50','Half day','Chill']},
{t:"Get a piercing done today",s:'Bonus points for people with no piercings yet',tags:['Solo','Friends','City','Under €20','30min','Chill']},
{t:"Buy a ticket to another country and leave today",s:'Solo or with the gang, this will be one heck of a story',tags:['Solo','Friends','Couple','Road Trip','Under €50','Multiple days','Active']},
{t:"Skinny dipping in the dark",s:'Katy Perry had it figured out',tags:['Friends','Couple','Outdoors','Nature','Free','Evening','Active']},
{t:"Dye your hair",s:'If you have been thinking about it, now is the time to do it!',tags:['Solo','Friends','Home','Indoors','City','Under €20','Half day','Chill']},
{t:"Go into a karaoke, but a friend picks a song for you",s:'Neaaar… FAaAaR…. wherEVeEeeEEER *dies*',tags:['Friends','City','Under €20','Evening','Active']},
{t:"Give one mentally unstable friend complete control over the day",s:'Trust is about to be tested',tags:['Friends','Varies','Varies','Full day','Active']},
{t:"Stay awake and go watch the sunrise somewhere random",s:'No sleep. No regrets',tags:['Friends','Couple','Solo','Outdoors','Nature','Free','30min','Active']},
{t:"Find the coldest river possible and jump in",s:'Everybody acts tough until the first toe enters',tags:['Friends','Outdoors','Nature','Free','30min','High Energy']},
{t:"Whoever loses rock paper scissors has to do one thing everyone is scared of",s:'Character development',tags:['Friends','Varies','Varies','Active']},
{t:"Buy an extra ticket to an event and convince a stranger to tag along",s:'Worst they can say is no',tags:['Solo','City','Under €50','Half day','Chill']},
{t:"Wear something you've never had the confidence to wear",s:'The outfit has been waiting. The moment is now',tags:['Solo','Friends','City','Free','Full day','Chill']},
{t:"Sleep in a completely different city tonight with no pre-booked accommodation",s:'Figure it out when you get there',tags:['Solo','Friends','City','Under €50','Multiple days','Active']},
{t:"Go to an airport, pick a destination when you get there",s:'Now this is true uncle lore',tags:['Solo','Friends','Road Trip','Expensive','Multiple days','Active']},
{t:"Truth or dare in public",s:'You can play with a skip, use it wisely…',tags:['Friends','City','Outdoors','Free','1 hour','Active']},
{t:"Sneak into an event",s:'This is not a life advice. Do it at your own risk',tags:['Friends','Solo','City','Free','Half day','Active']},
{t:"Tell someone something you've been meaning to say for a long time",s:'You know exactly who. You know exactly what',tags:['Solo','Free','30min','Chill']},
{t:"Apply for something you think you're not ready for",s:'The rejection is also an answer. Apply anyway',tags:['Solo','Home','Indoors','Free','1 hour','Lazy']},
{t:"Pick a discipline, whoever loses shaves their head",s:"Don't worry, hair grows back",tags:['Friends','Free','Varies','Active']},
{t:"Introduce yourself to every single person at the next event you go to",s:'Every. Single. One',tags:['Solo','Friends','City','Varies','Evening','Active']},
{t:"Book a one-way train ticket to anywhere and figure out the return later",s:'Get your backpacks ready, we are going… where exactly?',tags:['Solo','Friends','Road Trip','Under €20','Full day','Active']},
{t:"Invite a celebrity to your hangout or out for a drink",s:'Worst they can say is no',tags:['Solo','Friends','City','Free','1 hour','Chill']},
{t:"Go to a job interview for a job you don't actually want",s:'Practice lying confidently. Dress well',tags:['Solo','City','Free','Half day','Chill']},
{t:"Spend an entire day saying yes to everything anyone asks",s:'Set absolutely no boundaries and report back',tags:['Solo','Friends','Varies','Varies','Full day','Active']},
{t:"Do the thing you've been scared to do for months",s:'You already know what it is',tags:['Solo','Varies','Varies','Active']},
{t:"Go busking with zero musical ability",s:'A hat, a corner, and absolutely no shame',tags:['Friends','Solo','City','Outdoors','Free','Half day','Active']}
]},
selfimprovement:{label:'Self Improvement',emoji:'📈',c1:'#4ade80',c2:'#16a34a',glow:'rgba(74,222,128,.35)',ideas:[
{t:"Learn a new instrument",s:"Your fingers will hate you for a week. Then they won't",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Learn a foreign language",s:"The world gets 3x bigger when you can talk to more of it",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Start meditating",s:"Your brain has been running without a restart for years",tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Go for a run",s:"The first minute is the worst. Then it's only kind of bad",tags:['Solo','Outdoors','City','Nature','Free','30min','Active']},
{t:"Go to the gym",s:"The hardest rep is always the drive there",tags:['Solo','City','Under €20','1 hour','Active']},
{t:"Stretch",s:"Your back has filed several formal complaints",tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Do yoga",s:"It's not just for people who own crystals",tags:['Solo','Home','Indoors','Outdoors','Free','30min','Active']},
{t:"Learn 15 constellations",s:"So the next time you look up, the sky means something",tags:['Solo','Outdoors','Nature','Free','1 hour','Lazy']},
{t:"Read a book",s:"Your phone has the attention span of a goldfish. Be different",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Read philosophy",s:"Warning: may cause you to question everything, including this list",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Practice stress regulation",s:"The storm doesn't stop. You just get better at sailing",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Learn to cook a new dish",s:"Pick something impressive. Serve it like you've done it 100 times",tags:['Solo','Home','Indoors','Under €20','1 hour','Active']},
{t:"Rejection therapy",s:"Go get rejected on purpose today. It's cheaper than therapy",tags:['Solo','City','Free','Half day','Active']},
{t:"Take a cold shower",s:"Every morning you win this fight, you win the whole day",tags:['Solo','Home','Indoors','Free','15min','Active']},
{t:"Take a walk",s:"Most good ideas were born somewhere between here and there",tags:['Solo','Outdoors','City','Nature','Free','30min','Chill']},
{t:"Deep breathing",s:"You've been breathing wrong your whole life. Let's fix that",tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Plant a tree",s:"You'll never sit in its shade. Do it anyway",tags:['Solo','Outdoors','Nature','Under €10','1 hour','Active']},
{t:"Start a business",s:"The worst that happens is a great story. The best is everything",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy']},
{t:"Do something you've been meaning to do for a while",s:"You know what it is. It's been on the list for months",tags:['Solo','Varies','Varies','Active']},
{t:"Clean your room or house",s:"External chaos is just internal chaos with furniture",tags:['Solo','Home','Indoors','Free','Half day','Active']},
{t:"Start or improve your skincare",s:"Your face is the first thing people see. Treat it accordingly",tags:['Solo','Home','Indoors','Under €20','15min','Lazy']},
{t:"Upgrade your style",s:"You don't have to buy new things. Just wear them differently",tags:['Solo','City','Varies','Half day','Chill']},
{t:"Do your hobby",s:"Not for productivity. Not for content. Just because you like it",tags:['Solo','Home','Varies','Half day','Lazy']},
{t:"Start a side business",s:"One idea + one afternoon is how most of them begin",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy']},
{t:"Meet new people",s:"Every interesting person you know was once a stranger",tags:['Solo','City','Free','Half day','Active']},
{t:"Study for an exam",s:"Future you will be either grateful or furious. Choose which",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Learn to time manage",s:"There are actual techniques. They work. Nobody uses them",tags:['Solo','Home','Indoors','Free','1 hour','Lazy']},
{t:"Organize your tasks and write them down in a calendar",s:"Your brain is for thinking, not storage",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Start a 1-year project",s:"Pick something ambitious enough to scare you slightly",tags:['Solo','Home','Indoors','Varies','Ongoing','Lazy']},
{t:"Learn basic first aid",s:"Being useful in an emergency is genuinely attractive",tags:['Solo','City','Free','Half day','Active']},
{t:"Learn sign language",s:"Communication DLC. Seriously underrated",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Fix something that's broken",s:"Become the ancestor your bloodline deserves",tags:['Solo','Home','Indoors','Varies','Half day','Active']},
{t:"Learn how to identify birds, trees or mushrooms",s:"Touch grass, but professionally",tags:['Solo','Outdoors','Nature','Free','Half day','Active']},
{t:"Learn chess",s:"Destroy your friends intellectually",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Learn how to make really good coffee",s:"Barista arc incoming",tags:['Solo','Home','Indoors','Under €20','1 hour','Lazy']},
{t:"Learn how to whistle with your fingers",s:"Dads have guarded this knowledge for generations",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Start journaling",s:"Your thoughts deserve better storage than 3am",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Learn speed typing",s:"Become more efficient by at least 2x",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Learn how to sew",s:"Grandma wisdom strikes again. Also saves money",tags:['Solo','Home','Indoors','Under €10','1 hour','Lazy']},
{t:"Write down 30 things you want to do in life",s:"Your bucket list won't build itself",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Learn how to start a campfire",s:"Cavemen had no YouTube tutorials and they figured it out",tags:['Solo','Outdoors','Nature','Free','30min','Active']},
{t:"Improve your posture",s:"Your spine has filed several formal complaints",tags:['Solo','Home','Indoors','Free','15min','Lazy']},
{t:"Learn how to negotiate",s:"Everything is a side quest until money gets involved",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Master one signature dish",s:"Become legendary for something",tags:['Solo','Home','Indoors','Under €20','Half day','Active']},
{t:"Learn how to pick a lock",s:"For legal purposes, this is a hobby",tags:['Solo','Home','Indoors','Under €20','Half day','Lazy']},
{t:"Learn basic psychology",s:"Humans are weird. Including you. Especially you",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Improve your handwriting",s:"Doctors are not role models",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Learn one survival skill",s:"Knots, fire, water purification — pick one. Become suspiciously useful",tags:['Solo','Outdoors','Nature','Free','Half day','Active']},
{t:"Learn how to dance",s:"Embarrassment is temporary. Moves are forever",tags:['Solo','Home','Indoors','City','Free','Half day','Active']},
{t:"Learn how to edit videos",s:"Your future side hustle is watching",tags:['Solo','Home','Indoors','Free','Ongoing','Lazy']},
{t:"Learn one card trick",s:"Uncles have been abusing this power for decades",tags:['Solo','Home','Indoors','Free','30min','Lazy']},
{t:"Learn morse code",s:"Useless until suddenly incredibly useful",tags:['Solo','Home','Indoors','Free','Half day','Lazy']},
{t:"Learn how to change a tire",s:"This skill will save you on a dark road at midnight",tags:['Solo','Outdoors','Free','30min','Active']}
]}
};
